Foreground yes
User clamav
TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
LogTime yes
LogFile /tmp/clamd.log
PidFile /tmp/clamd.pid
DatabaseDirectory /var/lib/clamav
SelfCheck 600
ConcurrentDatabaseReload yes
MaxThreads 2
MaxQueue 8
StreamMaxLength 25M
MaxScanSize 100M
MaxFileSize 25M
MaxRecursion 12
MaxFiles 2000
ScanPDF yes
ScanArchive yes
ScanPE yes
ScanOLE2 yes
ScanHTML yes
AlertExceedsMax yes
AlertEncryptedDoc yes
ReadTimeout 60
CommandReadTimeout 30
