import { IBApi, EventName, OrderAction, OrderType, SecType, TimeInForce, WhatToShow } from '@stoqey/ib';

export class IBKRNewGateway {
  constructor(config, onEvent) { this.config = config; this.onEvent = onEvent; this.nextOrderId = null; this.connected = false; this.positions = []; this.openOrders = []; this.account = {}; this.orderMap = new Map(); this.executionMap = new Map(); this.ib = new IBApi({ host: config.host, port: config.port, clientId: config.clientId }); }
  connect() { return new Promise((resolve, reject) => { const timeout = setTimeout(() => reject(new Error('IBKRNew Gateway connection timeout')), 15000); this.ib.on(EventName.error, (e, code, reqId) => { if (Number(code) >= 500 && Number(reqId) === -1) this.onEvent('bridge.gateway_error', { component_id: 'IBKRNewGateway', component_type: 'ibkr_gateway', code, message: e?.message || String(e) }); }); this.ib.on(EventName.disconnected, () => { this.connected = false; this.onEvent('bridge.gateway_disconnected', { component_id: 'IBKRNewGateway', component_type: 'ibkr_gateway', message: 'IBKR Gateway disconnected' }); }); this.ib.on(EventName.nextValidId, (orderId) => { clearTimeout(timeout); this.connected = true; this.nextOrderId = Number(orderId); this.installCallbacks(); resolve(); }); this.ib.connect(); }); }
  installCallbacks() {
    this.ib.on(EventName.updateAccountValue, (key, value, currency) => { if (currency === 'USD' || !currency) this.account[key] = Number(value); });
    this.ib.on(EventName.updatePortfolio, (contract, position, marketPrice, marketValue, averageCost, unrealizedPNL, realizedPNL) => { const item = { con_id: contract.conId, symbol: contract.symbol, security_type: contract.secType, quantity: position, market_price: marketPrice, market_value: marketValue, average_cost: averageCost, unrealized_pnl_usd: unrealizedPNL, realized_pnl_usd: realizedPNL, multiplier: contract.multiplier }; this.positions = this.positions.filter((p) => p.con_id !== item.con_id); if (Number(position)) this.positions.push(item); this.onEvent('position.changed', { positions: this.positions }); });
    this.ib.on(EventName.openOrder, (orderId, contract, order, orderState) => { this.openOrders = this.openOrders.filter((x) => x.order_id !== Number(orderId)); this.openOrders.push({ order_id: Number(orderId), order_ref: order.orderRef, symbol: contract.symbol, status: orderState?.status, parent_id: order.parentId }); });
    this.ib.on(EventName.accountDownloadEnd, () => this.onEvent('account.snapshot', { eligible_capital_usd: this.account.NetLiquidation || 0, cash_usd: this.account.TotalCashValue || 0, realized_pnl_day_usd: this.account.RealizedPnL || 0, unrealized_pnl_usd: this.account.UnrealizedPnL || 0, positions: this.positions, open_orders: this.openOrders }));
    this.ib.on(EventName.orderStatus, (orderId, status, filled, remaining, avgFillPrice) => this.onEvent('order.status_changed', { order_id: orderId, ...this.orderMap.get(Number(orderId)), status, filled, remaining, average_fill_price: avgFillPrice }));
    this.ib.on(EventName.execDetails, (requestId, contract, execution) => { const mapped = this.orderMap.get(Number(execution.orderId)) || {}; const payload = { execution_id: execution.execId, order_id: execution.orderId, ...mapped, symbol: contract.symbol, side: execution.side, quantity: execution.shares, price: execution.price, occurred_at: execution.time }; this.executionMap.set(String(execution.execId), payload); this.onEvent('execution.fill', payload); });
    this.ib.on(EventName.commissionReport, (report) => { const mapped = this.executionMap.get(String(report.execId)) || {}; this.onEvent('commission.report', { execution_id: report.execId, ...mapped, commission_usd: report.commission, realized_pnl_usd: report.realizedPNL, currency: report.currency }); });
    this.ib.reqAccountUpdates(true, this.config.accountId); this.ib.reqAllOpenOrders();
  }
  contract(c) { const out = { conId: Number(c.con_id) || 0, symbol: c.symbol, secType: c.security_type === 'OPT' ? SecType.OPT : SecType.STK, exchange: c.exchange || 'SMART', currency: c.currency || 'USD' }; if (out.secType === SecType.OPT) Object.assign(out, { lastTradeDateOrContractMonth: c.expiry, strike: Number(c.strike), right: c.right, multiplier: String(c.multiplier || 100) }); return out; }
  snapshotQuote(contract) { return new Promise((resolve, reject) => { const requestId = 500000 + Math.floor(Math.random() * 400000); const quote = {}; const cleanup = () => { clearTimeout(timer); this.ib.off(EventName.tickPrice, onPrice); this.ib.off(EventName.tickSnapshotEnd, onEnd); try { this.ib.cancelMktData(requestId); } catch {} }; const finish = () => { cleanup(); const bid = Number(quote.bid); const ask = Number(quote.ask); const last = Number(quote.last); if (![bid, ask, last].some((x) => Number.isFinite(x) && x > 0)) reject(new Error('fresh local IBKR quote unavailable')); else resolve({ bid, ask, last, captured_at: new Date().toISOString() }); }; const onPrice = (id, field, value) => { if (id !== requestId || !(Number(value) > 0)) return; if (Number(field) === 1) quote.bid = value; if (Number(field) === 2) quote.ask = value; if (Number(field) === 4) quote.last = value; }; const onEnd = (id) => { if (id === requestId) finish(); }; const timer = setTimeout(finish, 6000); this.ib.on(EventName.tickPrice, onPrice); this.ib.on(EventName.tickSnapshotEnd, onEnd); this.ib.reqMktData(requestId, contract, '', true, false, []); }); }
  subscribe(symbol, requestId) { const contract = { symbol, secType: SecType.STK, exchange: 'SMART', currency: 'USD' }; this.ib.reqRealTimeBars(requestId, contract, 5, WhatToShow.TRADES, true, []); this.ib.reqMktData(requestId + 10000, contract, '236', false, false, []); this.ib.on(EventName.realtimeBar, (id, date, open, high, low, close, volume, wap, count) => { if (id === requestId) this.onEvent('market.realtime_bar', { symbol, interval_seconds: 5, at: new Date(Number(date) * 1000).toISOString(), open, high, low, close, volume, vwap: wap, count }); }); this.ib.on(EventName.tickGeneric, (id, field, value) => { if (id === requestId + 10000 && Number(field) === 46) this.onEvent('instrument.shortability_changed', { symbol, shortable: Number(value) > 0, shortable_shares: Number(value) }); }); }
  async placeProtected(command) { const a = command.authorization; if (a.environment !== 'paper' || !String(this.config.accountId).startsWith('DU')) throw new Error('IBKRNew refuses non-paper execution'); if (Date.parse(a.expires_at) <= Date.now()) throw new Error('authorization expired'); if (!a.protection?.stop_price || a.entry?.order_type !== 'LIMIT') throw new Error('bounded entry and protective stop required'); const contract = this.contract(a.contract); const quote = await this.snapshotQuote(contract); const reference = Number.isFinite(quote.ask) ? quote.ask : quote.last; if (a.side === 'BUY' && Number(a.entry.limit_price) > reference * 1.005) throw new Error('entry limit exceeds fresh local IBKR quote bound'); const sellReference = Number.isFinite(quote.bid) ? quote.bid : quote.last; if (a.side === 'SELL' && Number(a.entry.limit_price) < sellReference * 0.995) throw new Error('short entry limit is below fresh local IBKR quote bound'); const entryId = this.nextOrderId++; const targetId = this.nextOrderId++; const stopId = this.nextOrderId++; const exitAction = a.side === 'BUY' ? OrderAction.SELL : OrderAction.BUY; const target = a.protection.targets?.[0]; if (!target?.limit_price) throw new Error('profit target required'); const ocaGroup = `IBKRNew:${a.authorization_id}`; this.orderMap.set(entryId, { authorization_id: a.authorization_id, order_role: 'entry' }); this.orderMap.set(targetId, { authorization_id: a.authorization_id, order_role: 'target' }); this.orderMap.set(stopId, { authorization_id: a.authorization_id, order_role: 'protective_stop' }); this.ib.placeOrder(entryId, contract, { account: this.config.accountId, action: a.side === 'BUY' ? OrderAction.BUY : OrderAction.SSHORT, orderType: OrderType.LMT, totalQuantity: a.quantity, lmtPrice: a.entry.limit_price, tif: TimeInForce.DAY, transmit: false, orderRef: a.authorization_id }); this.ib.placeOrder(targetId, contract, { account: this.config.accountId, action: exitAction, orderType: OrderType.LMT, totalQuantity: a.quantity, lmtPrice: target.limit_price, parentId: entryId, ocaGroup, ocaType: 1, tif: TimeInForce.GTC, transmit: false, orderRef: a.authorization_id }); this.ib.placeOrder(stopId, contract, { account: this.config.accountId, action: exitAction, orderType: OrderType.STP, totalQuantity: a.quantity, auxPrice: a.protection.stop_price, parentId: entryId, ocaGroup, ocaType: 1, tif: TimeInForce.GTC, transmit: true, orderRef: a.authorization_id }); return { entry_order_id: entryId, target_order_id: targetId, protective_order_id: stopId, local_quote: quote }; }
  disconnect() { this.ib.disconnect(); }
  health() { return { connected: this.connected, account_id: this.config.accountId, positions: this.positions.length, open_orders: this.openOrders.length }; }
}
