import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import ActionFeedbackBanner from '../components/ActionFeedbackBanner';
import { useActionFeedback } from '../hooks/useActionFeedback';
import { useInfiniteScroll } from '../hooks/useInfiniteScroll';

const blank={name:'',advertiser:'Flolah',disclosure:'Promotional announcement',delivery:'popup',audience:'all',frequency:'once',frequency_cap:1,priority:0,state:'draft',starts_at:'',ends_at:'',allow_suppress:true,target_user_ids:[],blocks:[{type:'heading',text:''},{type:'paragraph',text:''},{type:'cta',label:'Learn more',url:''}]};
const types=['heading','paragraph','image','video','audio','cta','disclosure'];
const labels={heading:'Heading',paragraph:'Paragraph',image:'Image',video:'Video',audio:'Audio',cta:'Button',disclosure:'Disclosure'};

export default function AdminPromotions(){
  const [items,setItems]=useState([]),[form,setForm]=useState(blank),[editingId,setEditingId]=useState(null),[users,setUsers]=useState([]),[busy,setBusy]=useState(false),[analytics,setAnalytics]=useState(null),[userQuery,setUserQuery]=useState('');
  const [hasMore,setHasMore]=useState(false),[loadingMore,setLoadingMore]=useState(false);
  const {feedback,showSuccess,showError,clearFeedback}=useActionFeedback();
  const load=()=>Promise.all([api.adminPromotionsList({limit:20,offset:0}),api.adminUsers({limit:200})]).then(([a,u])=>{setItems(a.campaigns||[]);setHasMore(!!a.has_more);setUsers(u.users||[])}).catch(e=>showError(e.message));
  const loadMore=useCallback(async()=>{if(!hasMore||loadingMore)return;setLoadingMore(true);try{const a=await api.adminPromotionsList({limit:20,offset:items.length});setItems(current=>[...current,...(a.campaigns||[])]);setHasMore(!!a.has_more)}catch(e){showError(e.message)}finally{setLoadingMore(false)}},[hasMore,loadingMore,items.length,showError]);
  const sentinelRef=useInfiniteScroll(loadMore,hasMore&&!loadingMore);
  useEffect(()=>{load()},[]);
  const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  const setBlock=(i,key,value)=>setForm(current=>({...current,blocks:current.blocks.map((block,n)=>n===i?{...block,[key]:value}:block)}));
  const addBlock=type=>setForm(current=>({...current,blocks:[...current.blocks,{type,text:'',label:type==='cta'?'Learn more':'',url:'',alt:''}]}));
  const removeBlock=index=>setForm(current=>({...current,blocks:current.blocks.filter((_,n)=>n!==index)}));
  const reset=()=>{setEditingId(null);setForm(blank);clearFeedback()};
  const edit=campaign=>{setEditingId(campaign.id);setForm({...blank,...campaign,target_user_ids:campaign.target_user_ids||[],blocks:campaign.blocks||[]});window.scrollTo({top:0,behavior:'smooth'})};
  const save=async event=>{event.preventDefault();setBusy(true);try{editingId?await api.adminPromotionsUpdate(editingId,form):await api.adminPromotionsCreate(form);showSuccess('Campaign saved.');setForm(blank);setEditingId(null);await load()}catch(error){showError(error.message)}finally{setBusy(false)}};
  const filteredUsers=useMemo(()=>{const q=userQuery.trim().toLowerCase();return q?users.filter(user=>`${user.name||''} ${user.email||''}`.toLowerCase().includes(q)):users},[users,userQuery]);
  const toggleUser=id=>update('target_user_ids',form.target_user_ids.includes(id)?form.target_user_ids.filter(value=>value!==id):[...form.target_user_ids,id]);
  const loadEvidence=(campaignId,page=1)=>api.adminPromotionAnalytics(campaignId,{page,page_size:25}).then(setAnalytics).catch(e=>showError(e.message));
  return <div className="page page-wide promotions-admin">
    <header className="promotions-hero"><div><span className="promotions-eyebrow">Audience engagement</span><h1>Internal promotions</h1><p>Create disclosed, targeted announcements and see honest delivery and interaction evidence.</p></div>{editingId&&<button type="button" className="btn-secondary" onClick={reset}>Create new campaign</button>}</header>
    <ActionFeedbackBanner feedback={feedback} onDismiss={clearFeedback}/>
    <form className="promotions-layout" onSubmit={save}>
      <div className="promotions-main">
        <section className="card promotions-section"><header><span className="promotions-step">1</span><div><h2>Campaign details</h2><p>Name the promotion and make its sponsor clear.</p></div></header><div className="promotions-fields two-columns">
          <label><span>Campaign name</span><input value={form.name} onChange={e=>update('name',e.target.value)} required placeholder="e.g. Founder plan launch"/></label>
          <label><span>Advertiser</span><input value={form.advertiser} onChange={e=>update('advertiser',e.target.value)} required/></label>
          <label className="field-full"><span>Disclosure</span><input value={form.disclosure} onChange={e=>update('disclosure',e.target.value)} required/><small>Shown with the promotion so users know it is sponsored.</small></label>
        </div></section>
        <section className="card promotions-section"><header><span className="promotions-step">2</span><div><h2>Audience and delivery</h2><p>Choose who receives it, where it appears, and how often.</p></div></header><div className="promotions-fields two-columns">
          <label><span>Delivery</span><select value={form.delivery} onChange={e=>update('delivery',e.target.value)}><option value="popup">Login popup</option><option value="whatsapp">WhatsApp</option><option value="both">Popup and WhatsApp</option></select></label>
          <label><span>Audience</span><select value={form.audience} onChange={e=>update('audience',e.target.value)}><option value="all">All enabled users</option><option value="selected">Selected users</option></select></label>
          {form.audience==='selected'&&<div className="field-full promotions-user-picker"><label><span>Selected users</span><input type="search" value={userQuery} onChange={e=>setUserQuery(e.target.value)} placeholder="Search by name or email"/></label><div className="promotions-user-results" role="group" aria-label="Campaign recipients">{!filteredUsers.length&&<p>No matching users.</p>}{filteredUsers.map(user=><label key={user.id}><input type="checkbox" checked={form.target_user_ids.includes(user.id)} onChange={()=>toggleUser(user.id)}/><span><strong>{user.name}</strong><small>{user.email}</small></span></label>)}</div><small>{form.target_user_ids.length} selected</small></div>}
          <label><span>Frequency</span><select value={form.frequency} onChange={e=>update('frequency',e.target.value)}><option value="once">Once</option><option value="daily">Once daily</option><option value="capped">Capped</option></select></label>
          {form.frequency==='capped'&&<label><span>Maximum deliveries</span><input type="number" min="1" value={form.frequency_cap} onChange={e=>update('frequency_cap',Number(e.target.value))}/></label>}
        </div></section>
        <section className="card promotions-section"><header><span className="promotions-step">3</span><div><h2>Structured content</h2><p>Build the promotion in accessible, reusable blocks.</p></div></header><div className="promotion-block-list">
          {form.blocks.map((block,index)=><article className="promotion-block" key={`${block.type}-${index}`}><header><div><span className="promotion-block-number">{index+1}</span><strong>{labels[block.type]||block.type}</strong></div><button className="btn-ghost promotion-remove" type="button" onClick={()=>removeBlock(index)}>Remove</button></header>
            {['heading','paragraph','disclosure'].includes(block.type)&&<label><span>{block.type==='heading'?'Text':'Content'}</span><textarea rows={block.type==='heading'?2:4} value={block.text||''} onChange={e=>setBlock(index,'text',e.target.value)}/></label>}
            {['image','video','audio'].includes(block.type)&&<div className="promotions-fields two-columns"><label><span>Media URL</span><input placeholder="HTTPS media URL or /api/media path" value={block.url||''} onChange={e=>setBlock(index,'url',e.target.value)}/></label><label><span>{block.type==='image'?'Accessible description':'Transcript'}</span><input value={block.alt||block.text||''} onChange={e=>setBlock(index,block.type==='image'?'alt':'text',e.target.value)}/></label></div>}
            {block.type==='cta'&&<div className="promotions-fields two-columns"><label><span>Button label</span><input value={block.label||''} onChange={e=>setBlock(index,'label',e.target.value)}/></label><label><span>HTTPS destination</span><input type="url" value={block.url||''} onChange={e=>setBlock(index,'url',e.target.value)}/></label></div>}
          </article>)}
        </div><div className="promotion-add-blocks">{types.map(type=><button className="btn-secondary" type="button" key={type} onClick={()=>addBlock(type)}>+ {labels[type]}</button>)}</div></section>
      </div>
      <aside className="promotions-sidebar"><section className="card promotions-publish"><h2>Publish settings</h2>
        <label><span>State</span><select value={form.state} onChange={e=>update('state',e.target.value)}><option value="draft">Draft</option><option value="pending_approval">Pending approval</option><option value="scheduled">Scheduled</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>
        <label><span>Starts</span><input type="datetime-local" value={form.starts_at||''} onChange={e=>update('starts_at',e.target.value)}/></label><label><span>Ends</span><input type="datetime-local" value={form.ends_at||''} onChange={e=>update('ends_at',e.target.value)}/></label><label><span>Priority</span><input type="number" min="0" value={form.priority} onChange={e=>update('priority',Number(e.target.value))}/></label>
        <label className="promotion-check"><input type="checkbox" checked={form.allow_suppress!==false} onChange={e=>update('allow_suppress',e.target.checked)}/><span>Allow users to dismiss this promotion</span></label>
        <button className="btn-primary promotions-save" disabled={busy}>{busy?'Saving…':editingId?'Update campaign':'Save campaign'}</button>{editingId&&<button type="button" className="btn-ghost" onClick={reset}>Cancel editing</button>}
      </section></aside>
    </form>
    <section className="promotions-campaigns"><header><div><h2>Campaigns</h2><p>Review delivery state and evidence for previous promotions.</p></div><span>{items.length} loaded</span></header><div className="promotions-campaign-grid">{!items.length&&<div className="card promotions-empty">No campaigns yet.</div>}{items.map(campaign=><article className="card promotion-campaign" key={campaign.id}><header><div><h3>{campaign.name}</h3><p>{campaign.advertiser}</p></div><span className={`promotion-state state-${campaign.state}`}>{String(campaign.state||'draft').replaceAll('_',' ')}</span></header><p>{campaign.delivery} · {campaign.audience} · {campaign.frequency}</p><footer><button className="btn-secondary" onClick={()=>edit(campaign)}>Edit campaign</button><button className="btn-ghost" onClick={()=>loadEvidence(campaign.id)}>View evidence</button></footer></article>)}</div><div ref={sentinelRef} style={{minHeight:1}} aria-hidden="true"/>{hasMore&&<button type="button" className="btn-secondary" disabled={loadingMore} onClick={loadMore}>{loadingMore?'Loading…':'Load more campaigns'}</button>}</section>
    {analytics&&<section className="card promotions-evidence"><header><div><h2>Evidence: {analytics.campaign.name}</h2><p>Per-user delivery and interaction trail</p></div><button className="btn-ghost" onClick={()=>setAnalytics(null)}>Close</button></header><div className="promotions-evidence-totals">{analytics.totals.map((total,index)=><p key={index}><strong>{total.total}</strong><span>{total.event_type} / {total.channel}</span><small>{total.users} users</small></p>)}</div><div className="promotions-evidence-table-wrap"><table><thead><tr><th>User</th><th>Action</th><th>Channel</th><th>Time</th><th>Details</th></tr></thead><tbody>{!analytics.history.length&&<tr><td colSpan="5">No user activity recorded.</td></tr>}{analytics.history.map(event=><tr key={event.id}><td><strong>{event.user_name||'Unknown user'}</strong><small>{event.user_email||event.user_id}</small></td><td>{String(event.event_type).replaceAll('_',' ')}</td><td>{event.channel}</td><td>{new Date(event.created_at).toLocaleString()}</td><td>{event.metadata?.reason||event.metadata?.kind||'—'}</td></tr>)}</tbody></table></div>{analytics.pagination?.pages>1&&<footer className="promotions-evidence-pagination"><button type="button" className="btn-secondary" disabled={analytics.pagination.page<=1} onClick={()=>loadEvidence(analytics.campaign.id,analytics.pagination.page-1)}>Previous</button><span>Page {analytics.pagination.page} of {analytics.pagination.pages} · {analytics.pagination.total} events</span><button type="button" className="btn-secondary" disabled={analytics.pagination.page>=analytics.pagination.pages} onClick={()=>loadEvidence(analytics.campaign.id,analytics.pagination.page+1)}>Next</button></footer>}</section>}
  </div>
}
