import { useEffect, useState } from 'react';
import { api } from '../api';

const json = (v) => JSON.stringify(v || {}, null, 2);

export default function IBKRNewLiveOperations() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [accountId, setAccountId] = useState(''); const [credentials, setCredentials] = useState(null);
  const load = () => api.ibkrNewLiveOperations().then((x) => { setData(x); setError(''); }).catch((e) => setError(e.message));
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, []);
  const act = async (fn) => { setBusy(true); try { await fn(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const initialize = () => act(() => api.ibkrNewInitialize());
  const register = () => act(async () => { setCredentials(await api.ibkrNewRegisterBridge(accountId)); setAccountId(''); });
  const revoke = (id) => { if (window.confirm('Revoke this IBKRNew bridge and cancel its pending commands?')) act(() => api.ibkrNewRevokeBridge(id)); };
  const approve = (id) => act(() => api.ibkrNewApprove(id));
  const dashboard = data?.dashboard; const bridges = dashboard?.bridges || []; const budgets = dashboard?.budgets || {};
  return <div className="page page-wide ibkrnew-page">
    <header className="page-hero"><div className="page-hero-top"><div className="page-hero-titles"><p className="page-hero-kicker">Prebuilt Workflows · IBKRNew0</p><h1>Live operations</h1></div><span className="ibkrnew-environment">Paper only</span></div><p className="page-hero-sub">Desktop, bridge, Gateway, cached instrument profiles, positions, executions, approvals, and errors. History is retained for {data?.retention_days || '—'} days.</p></header>
    {error && <div className="page-banner page-banner-error" role="alert"><span>{error}</span><button type="button" className="btn-ghost" onClick={() => setError('')}>Dismiss</button></div>}
    {!dashboard && <button type="button" className="btn-primary" disabled={busy} onClick={initialize}>Initialize IBKRNew0</button>}
    <div className="this-week-grid">
      <section className="this-week-card"><small>Daily opening exposure</small><h2>${Number(budgets.daily_used_usd || 0).toFixed(2)}</h2><div>of ${Number(budgets.daily_limit_usd || 0).toFixed(2)}</div></section>
      <section className="this-week-card"><small>Total gross ceiling</small><h2>${Number(budgets.total_limit_usd || 0).toFixed(2)}</h2><div>Cash and positions combined</div></section>
      <section className="this-week-card"><small>IBKR account snapshot</small><h2>{dashboard?.account ? 'Received' : 'Waiting'}</h2><div>{dashboard?.account?.captured_at || 'No broker state'}</div></section>
      <section className="this-week-card"><small>Bridge</small><h2>{bridges[0]?.effective_status || 'Not registered'}</h2><div>{bridges[0]?.last_seen_at || 'A local desktop bridge is required'}</div></section>
    </div>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Dedicated desktop bridge</h2><div className="ibkrnew-inline-form"><input value={accountId} onChange={(e) => setAccountId(e.target.value)} placeholder="DU-prefixed paper account ID" /><button type="button" className="btn-primary" disabled={busy || !accountId.trim()} onClick={register}>Create credentials</button></div><p className="page-muted">Credentials are isolated to IBKRNew0 and the token is shown only once.</p>{credentials && <pre className="ibkrnew-pre">{json(credentials)}</pre>}{bridges.map((x) => <article key={x.bridge_id} className="ibkrnew-list-item"><strong>{x.account_id}</strong><span>{x.effective_status} · sequence {x.last_sequence}</span><small>{x.bridge_id}</small>{!x.revoked_at && <button type="button" className="btn-ghost btn-sm" disabled={busy} onClick={() => revoke(x.bridge_id)}>Revoke</button>}</article>)}</section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Pending CEO approvals</h2>{(dashboard?.approvals || []).length === 0 ? <p className="page-muted">None.</p> : dashboard.approvals.map((x) => <article className="ibkrnew-list-item" key={x.authorization_id}><strong>{x.expression}</strong><span>Expires {x.expires_at}</span><button type="button" className="btn-primary btn-sm" disabled={busy} onClick={() => approve(x.authorization_id)}>Approve once</button></article>)}</section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Component health</h2><div className="this-week-grid">{(data?.health || []).map((x) => <article key={`${x.bridge_id}-${x.component_id}`}><strong>{x.component_id}</strong><div>{x.component_type} · <span className="ibkrnew-status">{x.effective_status}</span></div><small>Last seen {x.last_seen_at} · errors {x.error_count}</small>{x.last_error && <p className="error-text">{x.last_error}</p>}</article>)}</div></section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Cached universe profiles</h2><div className="ibkrnew-table-wrap"><table className="ibkrnew-table"><thead><tr><th>Symbol</th><th>Type</th><th>Fundamentals</th><th>Membership</th><th>Corporate events</th><th>Updated</th></tr></thead><tbody>{(data?.instrument_profiles || []).map((x) => <tr key={`${x.symbol}-${x.security_type}`}><td><strong>{x.symbol}</strong></td><td>{x.security_type}</td><td>{x.fundamentals_at || 'Missing'}</td><td>{x.membership_at || 'Not required'}</td><td>{x.corporate_events_at || 'Missing'}</td><td>{x.updated_at}</td></tr>)}</tbody></table>{!data?.instrument_profiles?.length && <p className="page-muted">Waiting for the desktop bridge to refresh instrument profiles.</p>}</div></section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Current positions</h2><pre className="ibkrnew-pre">{json(dashboard?.account?.positions)}</pre></section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Position and account snapshots</h2>{(data?.snapshots || []).slice(0, 30).map((x) => <details key={x.snapshot_id}><summary>{x.captured_at} · {x.snapshot_type}</summary><pre className="ibkrnew-pre">{json(x.payload)}</pre></details>)}</section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Executions and commissions</h2><div className="ibkrnew-table-wrap"><table className="ibkrnew-table"><thead><tr><th>Time</th><th>Execution</th><th>Role</th><th>Side</th><th>Qty</th><th>Price</th><th>Commission</th><th>Realized P&amp;L</th></tr></thead><tbody>{(data?.executions || []).map((x) => <tr key={x.execution_id}><td>{x.occurred_at}</td><td>{x.execution_id}</td><td>{x.order_role}</td><td>{x.side}</td><td>{x.quantity}</td><td>{x.price}</td><td>{x.commission_usd}</td><td>{x.realized_pnl_usd}</td></tr>)}</tbody></table></div></section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Desktop and bridge errors</h2>{(data?.errors || []).map((x) => <article key={x.error_id} className="ibkrnew-list-item"><strong>{x.component_id} · {x.error_code || 'ERROR'}</strong><span>{x.message}</span><small>{x.occurred_at}</small></article>)}</section>
    <section className="panel ibkrnew-section"><h2 className="panel-title">Causal event timeline</h2>{(dashboard?.events || []).map((x) => <article key={x.event_id} className="ibkrnew-list-item"><strong>{x.event_type}</strong><span>{x.status} · sequence {x.sequence}</span><small>{x.event_id} · {x.occurred_at}</small>{x.reason && <p className="error-text">{x.reason}</p>}</article>)}</section>
  </div>;
}
