import { useEffect, useState } from 'react';
import { api } from '../api';

const money = (n) => `$${Number(n || 0).toFixed(2)}`;
export default function IBKRNewSummary() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.ibkrNewSummary().then(setData).catch((e) => setError(e.message)); }, []);
  const t = data?.totals || {};
  return <div style={{ padding: 24, maxWidth: 1300, margin: '0 auto' }}><h1>IBKRNew0 · Summary</h1><p>Commission-adjusted trading outcomes and allocation decisions. These records follow your profile retention policy ({data?.retention_days || '—'} days).</p>{error && <p className="error-text">{error}</p>}<div className="this-week-grid"><section className="this-week-card"><small>Trades</small><h2>{t.trade_count || 0}</h2></section><section className="this-week-card"><small>Gross P&amp;L</small><h2>{money(t.gross_pnl_usd)}</h2></section><section className="this-week-card"><small>Actual commissions</small><h2>{money(t.actual_commission_usd)}</h2></section><section className="this-week-card"><small>Net P&amp;L</small><h2>{money(t.net_pnl_usd)}</h2></section></div><section className="this-week-card"><h3>Trade history</h3><div style={{ overflowX: 'auto' }}><table><thead><tr><th>Time</th><th>Symbol</th><th>Expression</th><th>Status</th><th>Qty</th><th>Est. commission</th><th>Actual commission</th><th>Required profitable exit</th><th>Gross P&amp;L</th><th>Net P&amp;L</th></tr></thead><tbody>{(data?.trades || []).map((x) => <tr key={x.trade_id}><td>{x.created_at}</td><td>{x.symbol}</td><td>{x.expression}</td><td>{x.status}</td><td>{x.quantity}</td><td>{money(x.estimated_round_trip_commission_usd)}</td><td>{money(x.actual_commission_usd)}</td><td>{money(x.required_profitable_exit_price)}</td><td>{money(x.gross_pnl_usd)}</td><td>{money(x.net_pnl_usd)}</td></tr>)}</tbody></table></div></section><section className="this-week-card"><h3>Allocation decisions</h3>{(data?.allocations || []).map((x) => <article key={x.decision_id} style={{ borderTop: '1px solid var(--border)', padding: '10px 0' }}><strong>{x.allocation_mode}</strong> · {x.requested_quantity} requested / {x.approved_quantity} approved · net {money(x.expected_net_profit_usd)} · commission {money(x.estimated_commission_usd)}<div>{x.rationale}</div></article>)}</section></div>;
}
