import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api';

const PAGE = 12;
const periods = [['monthly','Monthly'],['quarterly','Quarterly'],['half_yearly','Half-yearly'],['annual','Annual']];
const money = (value, currency = 'SGD') => new Intl.NumberFormat('en-SG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value) || 0);
const pretty = (value) => String(value || '').replaceAll('_', ' ');
const today = new Date().toISOString().slice(0, 10);
const endOfYear = `${new Date().getFullYear()}-12-31`;
const formSourceFormula = (source, formulaId) => source?.formulas?.find((item) => item.id === formulaId)?.description || 'Choose a source to see its supported calculations.';

function Progress({ value = 0 }) { return <div className="objective-progress" aria-label={`${value}% complete`}><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }

export function ObjectivesList() {
  const [page, setPage] = useState(0), [period, setPeriod] = useState(''), [status, setStatus] = useState('');
  const [data, setData] = useState({ objectives: [], total: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [demoBusy, setDemoBusy] = useState(false);
  const load = () => { setLoading(true); api.companyObjectivesList({ limit: PAGE, offset: page * PAGE, period_type: period, status }).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, [page, period, status]);
  return <div className="digest-page objectives-page"><header className="digest-header"><div><h1 className="digest-title">Objectives Key Results (OKR)</h1><p className="digest-sub">Turn company outcomes into measurable key results, continuing initiatives and governed execution.</p></div><div className="digest-header-tools"><Link className="btn secondary" to="/objectives/measurement-registry">Measurement registry</Link><Link className="btn primary" to="/objectives/new">New objective</Link><button className="btn secondary" disabled={demoBusy} onClick={async()=>{setDemoBusy(true);setError('');try{await api.companyObjectiveBootstrapNorthstar();load();}catch(e){setError(e.message);}finally{setDemoBusy(false);}}}>{demoBusy?'Setting up…':'Set up Northstar demo'}</button></div></header>
    <section className="this-week-card objective-filters"><label>Period<select value={period} onChange={(e)=>{setPeriod(e.target.value);setPage(0);}}><option value="">All periods</option>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(0);}}><option value="">All statuses</option>{['draft','active','paused','completed'].map(v=><option key={v}>{v}</option>)}</select></label></section>
    {error&&<div className="error-box">{error}</div>}{loading?<p>Loading objectives…</p>:data.objectives.length===0?<section className="empty-state"><h2>No objectives yet</h2><p>Create one in Objective Studio or install the safe reference demo.</p></section>:<div className="objective-card-grid">{data.objectives.map(o=>{const lead=o.key_results?.[0];return <Link className="this-week-card objective-card" to={`/objectives/${encodeURIComponent(o.id)}`} key={o.id}><div className="objective-card-top"><span className={`objective-status status-${o.health}`}>{pretty(o.health)}</span><span>{o.period_label}</span></div><h2>{o.name}</h2><p>{o.outcome}</p>{lead&&<><Progress value={lead.progress_pct}/><strong>{lead.current_value} / {lead.target} {lead.unit}</strong></>}<footer><span>{o.key_results?.length||0} key results</span><span>{o.initiatives?.length||0} initiatives</span><span>{o.revenue?.awaiting_approval||0} approvals</span></footer></Link>;})}</div>}
    <div className="objective-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.total?`${page*PAGE+1}–${Math.min(data.total,(page+1)*PAGE)} of ${data.total}`:'0'}</span><button disabled={!data.has_more} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </div>;
}

export function ObjectiveStudio() {
  const navigate=useNavigate(); const [form,setForm]=useState({outcome:'Generate S$100k qualified pipeline this quarter. Target Singapore SMEs. Do not send external communications without approval.',period_type:'quarterly',period_label:'Q4 2026',starts_on:'2026-10-01',ends_on:'2026-12-31',currency:'SGD',budget_amount:450});
  const [proposal,setProposal]=useState(null),[busy,setBusy]=useState(false),[goalBusy,setGoalBusy]=useState({}),[error,setError]=useState(''),[model,setModel]=useState(''),[measurementSources,setMeasurementSources]=useState([]);
  useEffect(()=>{api.companyObjectiveMeasurementRegistry().then(r=>setMeasurementSources(r.sources||[])).catch(()=>setMeasurementSources([]));},[]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const updateKr=(index,patch)=>setProposal(p=>({...p,key_results:p.key_results.map((item,n)=>n===index?{...item,...patch}:item)}));
  const addKr=()=>setProposal(p=>({...p,key_results:[...(p.key_results||[]),{id:`kr-${crypto.randomUUID()}`,name:'New measurable result',definition:'',baseline:0,target:1,current_value:0,unit:'count',source_type:'business_events',formula:'count',confidence:'medium'}]}));
  const updateInitiative=(index,patch)=>setProposal(p=>({...p,initiatives:p.initiatives.map((item,n)=>n===index?{...item,...patch}:item)}));
  const addInitiative=()=>setProposal(p=>({...p,initiatives:[...(p.initiatives||[]),{id:`initiative-${crypto.randomUUID()}`,name:'New initiative',owner_label:'COO',cadence:'On demand',prompt:'',status:'draft',goals:[]}]}));
  const addGoal=(initiativeIndex)=>setProposal(p=>({...p,initiatives:p.initiatives.map((initiative,n)=>n===initiativeIndex?{...initiative,goals:[...(initiative.goals||[]),{id:`ig-${crypto.randomUUID()}`,goal_type:'adhoc',title:'New goal',prompt:'Define the completed outcome, evidence required, allowed writes, approval gates and exception handling.',owner_label:initiative.owner_label||'COO',agent_id:'',cadence:'weekdays',time_local:'09:00',timezone:'Asia/Singapore',linked_key_result_ids:[],approval_required:false,enabled:true}]}:initiative)}));
  const updateGoal=(initiativeIndex,goalIndex,patch)=>setProposal(p=>({...p,initiatives:p.initiatives.map((initiative,n)=>n===initiativeIndex?{...initiative,goals:(initiative.goals||[]).map((goal,g)=>g===goalIndex?{...goal,...patch}:goal)}:initiative)}));
  const removeGoal=(initiativeIndex,goalIndex)=>setProposal(p=>({...p,initiatives:p.initiatives.map((initiative,n)=>n===initiativeIndex?{...initiative,goals:(initiative.goals||[]).filter((_,g)=>g!==goalIndex)}:initiative)}));
  const generateGoals=async(initiativeIndex)=>{const initiative=proposal.initiatives[initiativeIndex];setGoalBusy(s=>({...s,[initiativeIndex]:true}));setError('');try{const r=await api.companyObjectiveIdeateGoals({objective:{...proposal,authority:proposal.authority,constraints:proposal.constraints},initiative,key_results:proposal.key_results,preferences:{timezone:'Asia/Singapore',cadence:'weekdays',time_local:'09:00'}});updateInitiative(initiativeIndex,{goals:r.goals||[]});setModel(`${r.model_used}${r.fallback?' · safe fallback':''}`);}catch(e){setError(e.message);}finally{setGoalBusy(s=>({...s,[initiativeIndex]:false}));}};
  const move=(key,index,direction)=>setProposal(p=>{const items=[...(p[key]||[])],to=index+direction;if(to<0||to>=items.length)return p;[items[index],items[to]]=[items[to],items[index]];return {...p,[key]:items};});
  const ideate=async()=>{setBusy(true);setError('');try{const r=await api.companyObjectiveIdeate(form);setProposal(r.proposal);setModel(r.model_used+(r.fallback?' · safe fallback':''));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const save=async(status)=>{setBusy(true);setError('');try{const p=proposal||form;const r=await api.companyObjectiveCreate({...p,period_type:p.periodType||p.period_type,period_label:p.periodLabel||p.period_label,starts_on:p.startsOn||p.starts_on,ends_on:p.endsOn||p.ends_on,status});navigate(`/objectives/${encodeURIComponent(r.objective.id)}`);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">Objective Studio</h1><p className="digest-sub">Define what success means before Goal Plans decide how to execute it.</p></div></header>{error&&<div className="error-box">{error}</div>}
    <section className="this-week-card objective-studio-form"><label className="wide">Business outcome<textarea rows="4" value={form.outcome} onChange={e=>set('outcome',e.target.value)}/></label><label>Period<select value={form.period_type} onChange={e=>set('period_type',e.target.value)}>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Period label<input value={form.period_label} onChange={e=>set('period_label',e.target.value)}/></label><label>Starts<input type="date" value={form.starts_on||today} onChange={e=>set('starts_on',e.target.value)}/></label><label>Ends<input type="date" value={form.ends_on||endOfYear} onChange={e=>set('ends_on',e.target.value)}/></label><label>Currency<input value={form.currency} maxLength="8" onChange={e=>set('currency',e.target.value)}/></label><label>AI/tool budget<input type="number" min="0" value={form.budget_amount} onChange={e=>set('budget_amount',Number(e.target.value))}/></label><div className="wide"><button className="btn primary" disabled={busy||!form.outcome.trim()} onClick={ideate}>{busy?'Designing…':'Generate objective proposal'}</button></div></section>
    {proposal&&<section className="this-week-card objective-proposal"><div className="objective-pulse-head"><div><h2>{proposal.name}</h2><p>{proposal.outcome}</p></div><small>{model}</small></div>
      <div className="objective-editor-heading"><div><h3>Key results</h3><p>Define measurable outcomes. Flolah updates each result from its selected business-data source.</p></div><button className="btn secondary" type="button" onClick={addKr}>Add key result</button></div>
      <div className="objective-edit-list">{proposal.key_results?.map((k,i)=>{
        const selectedSource=measurementSources.find(s=>s.id===k.source_type)||measurementSources.find(s=>s.formulas?.some(f=>f.id===k.formula));
        const formulas=selectedSource?.formulas||[],instances=selectedSource?.instances||[];
        return <article className="objective-edit-card" key={`kr-${i}`}>
          <div className="objective-edit-card-top"><span>KR {i+1}</span><div><button type="button" disabled={i===0} onClick={()=>move('key_results',i,-1)} aria-label={`Move key result ${i+1} up`}>↑</button><button type="button" disabled={i===proposal.key_results.length-1} onClick={()=>move('key_results',i,1)} aria-label={`Move key result ${i+1} down`}>↓</button><button type="button" className="danger-link" onClick={()=>setProposal(p=>({...p,key_results:p.key_results.filter((_,n)=>n!==i)}))}>Remove</button></div></div>
          <label className="wide">Result name<input value={k.name||''} onChange={e=>updateKr(i,{name:e.target.value})}/></label><label>Baseline<input type="number" value={k.baseline??0} onChange={e=>updateKr(i,{baseline:Number(e.target.value)})}/></label><label>Target<input type="number" min="0" value={k.target??0} onChange={e=>updateKr(i,{target:Number(e.target.value)})}/></label><label>Unit<input value={k.unit||''} onChange={e=>updateKr(i,{unit:e.target.value})}/></label>
          <label>Measurement source<select value={selectedSource?.id||''} onChange={e=>{const source=measurementSources.find(s=>s.id===e.target.value),instance=source?.instances?.[0];updateKr(i,{source_type:e.target.value,formula:source?.formulas?.[0]?.id||'',measurement_config:{...(k.measurement_config||{}),provider:source?.provider,instance_id:instance?.id||'',window:'objective_period',refresh:'event_driven',provenance:true}});}}><option value="" disabled>Select an authoritative source</option>{[...new Set(measurementSources.map(s=>s.category))].map(category=><optgroup label={category} key={category}>{measurementSources.filter(s=>s.category===category).map(source=><option value={source.id} key={source.id}>{source.label} · {source.availability==='available'?'available':'setup required'}</option>)}</optgroup>)}</select><small>{selectedSource?.provider||'Choose a registered source'}</small></label>
          <label>Specific company source<select value={k.measurement_config?.instance_id||instances[0]?.id||''} disabled={!instances.length} onChange={e=>updateKr(i,{measurement_config:{...(k.measurement_config||{}),instance_id:e.target.value,provider:selectedSource?.provider,window:'objective_period',refresh:'event_driven',provenance:true}})}><option value="">{instances.length?'Select a source instance':'Connect or configure this source'}</option>{instances.map(instance=><option value={instance.id} key={instance.id}>{instance.label}</option>)}</select><small>{instances.length?`${instances.length} company-scoped source${instances.length===1?'':'s'} available`:'No usable company source connected'}</small></label>
          <label>Measurement formula<select value={k.formula||''} onChange={e=>updateKr(i,{formula:e.target.value})}><option value="" disabled>Select how to calculate</option>{formulas.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select><small>{formSourceFormula(selectedSource,k.formula)}</small></label>
          <label className="wide">Definition<input value={k.definition||''} onChange={e=>updateKr(i,{definition:e.target.value})} placeholder="Exactly what counts and where the evidence comes from"/></label><div className="wide objective-measurement-contract"><span>Window: objective period</span><span>Refresh: event driven</span><span>Provenance: required</span></div>
        </article>;})}</div>
      <div className="objective-editor-heading"><div><h3>Initiatives</h3><p>Define the coordinated bodies of work that will produce the Key Results. Scheduling happens beneath each initiative.</p></div><button className="btn secondary" type="button" onClick={addInitiative}>Add initiative</button></div>
      <div className="objective-edit-list">{proposal.initiatives?.map((item,i)=>{const goals=item.goals||[];const agents=measurementSources.find(source=>source.id==='agents')?.instances||[];return <article className="objective-edit-card" key={item.id||`initiative-${i}`}>
        <div className="objective-edit-card-top"><span>Initiative {i+1}</span><div><button type="button" disabled={i===0} onClick={()=>move('initiatives',i,-1)} aria-label={`Move initiative ${i+1} up`}>↑</button><button type="button" disabled={i===proposal.initiatives.length-1} onClick={()=>move('initiatives',i,1)} aria-label={`Move initiative ${i+1} down`}>↓</button><button type="button" className="danger-link" onClick={()=>setProposal(p=>({...p,initiatives:p.initiatives.filter((_,n)=>n!==i)}))}>Remove</button></div></div>
        <label className="wide">Initiative name<input value={item.name||''} onChange={e=>updateInitiative(i,{name:e.target.value})}/></label><label>Accountable owner<input value={item.owner_label||''} onChange={e=>updateInitiative(i,{owner_label:e.target.value})}/></label><label>Operating mode<input value={item.cadence||''} onChange={e=>updateInitiative(i,{cadence:e.target.value})} placeholder="Continuous, time-bound, or event-led"/></label><label className="wide">Execution brief<textarea rows="2" value={item.prompt||''} onChange={e=>updateInitiative(i,{prompt:e.target.value})}/></label>
        <div className="wide objective-goals-editor"><div className="objective-editor-heading"><div><h4>Goals</h4><p>AI uses this Objective, Initiative, KRs, period, authority, available agents and existing goals. Review every recommendation before activation.</p></div><div><button className="btn secondary" type="button" disabled={goalBusy[i]} onClick={()=>generateGoals(i)}>{goalBusy[i]?'Generating…':goals.length?'Regenerate with AI':'Generate with AI'}</button><button className="btn secondary" type="button" onClick={()=>addGoal(i)}>Add goal manually</button></div></div>
          {!goals.length&&<p className="digest-muted">No goals yet. Generate recommendations or add one manually; an Initiative may have many scheduled and ad-hoc goals.</p>}
          {goals.map((goal,g)=><article className="objective-goal-editor" key={goal.id||g}><div className="objective-edit-card-top"><span>Goal {g+1} · {goal.goal_type==='scheduled'?'Scheduled':'Ad-hoc'}</span><button type="button" className="danger-link" onClick={()=>removeGoal(i,g)}>Remove</button></div>
            <label>Goal type<select value={goal.goal_type||'adhoc'} onChange={e=>updateGoal(i,g,{goal_type:e.target.value})}><option value="scheduled">Scheduled recurring goal</option><option value="adhoc">Ad-hoc goal</option></select></label><label>Accountable owner<input value={goal.owner_label||''} onChange={e=>updateGoal(i,g,{owner_label:e.target.value})}/></label><label className="wide">Goal title<input value={goal.title||''} onChange={e=>updateGoal(i,g,{title:e.target.value})}/></label><label>Assigned AI employee<select value={goal.agent_id||''} onChange={e=>updateGoal(i,g,{agent_id:e.target.value})}><option value="">Assign when executed</option>{agents.map(agent=><option value={agent.id} key={agent.id}>{agent.label}</option>)}</select></label><label className="objective-schedule-toggle"><input type="checkbox" checked={goal.approval_required===true} onChange={e=>updateGoal(i,g,{approval_required:e.target.checked})}/><span>Human approval before external action</span></label>
            {goal.goal_type==='scheduled'&&<><label>Cadence<select value={goal.cadence||'weekdays'} onChange={e=>updateGoal(i,g,{cadence:e.target.value})}><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option></select></label><label>Local time<input type="time" value={goal.time_local||'09:00'} onChange={e=>updateGoal(i,g,{time_local:e.target.value})}/></label><label>Timezone<input value={goal.timezone||'Asia/Singapore'} onChange={e=>updateGoal(i,g,{timezone:e.target.value})}/></label></>}
            <fieldset className="wide objective-kr-links"><legend>Contributes to Key Results</legend>{proposal.key_results.map((kr,k)=><label key={kr.id||k}><input type="checkbox" checked={(goal.linked_key_result_ids||[]).includes(kr.id)} onChange={e=>updateGoal(i,g,{linked_key_result_ids:e.target.checked?[...(goal.linked_key_result_ids||[]),kr.id]:(goal.linked_key_result_ids||[]).filter(id=>id!==kr.id)})}/><span>KR {k+1}: {kr.name}</span></label>)}</fieldset><label className="wide">Execution guidance<textarea rows="5" value={goal.prompt||''} onChange={e=>updateGoal(i,g,{prompt:e.target.value})}/><small>Include done criteria, evidence/provenance, allowed writes, approval gates and exception behavior.</small></label>
          </article>)}
        </div>
      </article>;})}</div>
      <details className="objective-boundaries"><summary><strong>Objective-specific execution boundaries</strong></summary><p>These boundaries narrow execution for this outcome. They cannot override company Policy, employee work assignments, or Exception Policy.</p><dl><div><dt>Company Policy</dt><dd>Controls what is permitted across the company.</dd></div><div><dt>Work assignments</dt><dd>Control which employee or agent is responsible and what tools they may use.</dd></div><div><dt>Exception Policy</dt><dd>Controls what happens when work is blocked, uncertain, or outside authority.</dd></div><div><dt>This Objective</dt><dd>Adds narrower limits such as budget, approved market, and no external sends without approval.</dd></div></dl><ul>{proposal.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul></details>
      <div className="objective-actions"><button className="btn secondary" disabled={busy||!proposal.key_results?.length} onClick={()=>save('draft')}>Save draft</button><button className="btn primary" disabled={busy||!proposal.key_results?.length||!proposal.initiatives?.length} onClick={()=>save('active')}>Approve and operate</button></div></section>}
  </div>;
}

export function MeasurementRegistryAdmin() {
  const emptySource={kind:'source',id:'',label:'',category:'Company configured',provider:'',description:'',enabled:true};
  const emptyAttribute={kind:'attribute',id:'',source_id:'',object_id:'',label:'',data_type:'',mapping_path:'',description:'',enabled:true};
  const emptyFormula={kind:'formula',id:'',source_id:'',label:'',expression:'',description:'',enabled:true};
  const [registry,setRegistry]=useState({sources:[]}),[source,setSource]=useState(emptySource),[attributeEntry,setAttributeEntry]=useState(emptyAttribute),[formulaEntry,setFormulaEntry]=useState(emptyFormula),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=()=>api.companyObjectiveMeasurementRegistry().then(setRegistry);
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  const save=async(entry,reset)=>{setBusy(true);setMessage('');try{setRegistry(await api.companyObjectiveMeasurementRegistrySave(entry));reset();setMessage('Company measurement registry saved.');}catch(e){setMessage(e.message);}finally{setBusy(false);}};
  const remove=async(kind,id)=>{if(!window.confirm('Remove this company registry entry? Existing Key Results keep their stored configuration.'))return;setBusy(true);try{setRegistry(await api.companyObjectiveMeasurementRegistryDelete(kind,id));}catch(e){setMessage(e.message);}finally{setBusy(false);}};
  const custom=registry.sources.filter(item=>item.company_managed),system=registry.sources.filter(item=>item.system_managed);
  const catalogueSources=registry.sources.filter(item=>item.objects?.length),selectedAttributeSource=catalogueSources.find(item=>item.id===attributeEntry.source_id),selectedObject=selectedAttributeSource?.objects?.find(item=>item.id===attributeEntry.object_id),ruleTemplate=registry.rule_templates?.[0],ruleInstalled=registry.rules?.some(item=>item.id===ruleTemplate?.id);
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives Key Results (OKR)</Link><h1 className="digest-title">Measurement Registry</h1><p className="digest-sub">Company administrators manage reusable measurement sources and formulas. Platform baselines remain inherited and read-only.</p></div></header>{message&&<div className={message.includes('saved')?'success-box':'error-box'} role="status">{message}</div>}
    <section className="objective-registry-grid"><article className="this-week-card"><h2>Add company source</h2><div className="objective-studio-form"><label>Source ID<input value={source.id} onChange={e=>setSource({...source,id:e.target.value})} placeholder="sales_warehouse"/></label><label>Label<input value={source.label} onChange={e=>setSource({...source,label:e.target.value})}/></label><label>Category<input value={source.category} onChange={e=>setSource({...source,category:e.target.value})}/></label><label>Provider<input value={source.provider} onChange={e=>setSource({...source,provider:e.target.value})}/></label><label className="wide">Description<textarea rows="2" value={source.description} onChange={e=>setSource({...source,description:e.target.value})}/></label><button className="btn primary" disabled={busy||!source.id||!source.label} onClick={()=>save(source,()=>setSource(emptySource))}>Save source</button></div></article>
    <article className="this-week-card"><h2>Add supported attribute</h2><p className="digest-muted">Select a provider-backed object field. IDs and paths cannot be typed manually.</p><div className="objective-studio-form"><label>Source<select value={attributeEntry.source_id} onChange={e=>setAttributeEntry({...emptyAttribute,source_id:e.target.value})}><option value="">Select source</option>{catalogueSources.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Object<select value={attributeEntry.object_id} disabled={!selectedAttributeSource} onChange={e=>setAttributeEntry({...emptyAttribute,source_id:attributeEntry.source_id,object_id:e.target.value})}><option value="">Select object</option>{selectedAttributeSource?.objects?.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="wide">Supported field<select value={attributeEntry.id} disabled={!selectedObject} onChange={e=>{const field=selectedObject?.attributes?.find(item=>item.id===e.target.value);setAttributeEntry(field?{kind:'attribute',source_id:attributeEntry.source_id,object_id:selectedObject.id,id:field.id,label:field.label,data_type:field.data_type,mapping_path:field.path,description:field.description,enabled:true}:{...emptyAttribute,source_id:attributeEntry.source_id,object_id:selectedObject?.id||''});}}><option value="">Select field</option>{selectedObject?.attributes?.map(item=><option value={item.id} key={item.id}>{item.label} · {item.path}</option>)}</select></label><label>Registry attribute ID<input readOnly value={attributeEntry.id}/></label><label>Provider mapping path<input readOnly value={attributeEntry.mapping_path}/></label><label>Data type<input readOnly value={pretty(attributeEntry.data_type)}/></label><label className="wide">Description<textarea readOnly rows="2" value={attributeEntry.description}/></label><button className="btn primary" disabled={busy||!attributeEntry.source_id||!attributeEntry.object_id||!attributeEntry.id} onClick={()=>save(attributeEntry,()=>setAttributeEntry(emptyAttribute))}>Add catalogue field</button></div></article>
    <article className="this-week-card"><h2>Add company formula</h2><div className="objective-studio-form"><label>Source<select value={formulaEntry.source_id} onChange={e=>setFormulaEntry({...formulaEntry,source_id:e.target.value})}><option value="">Select source</option>{registry.sources.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Formula ID<input value={formulaEntry.id} onChange={e=>setFormulaEntry({...formulaEntry,id:e.target.value})} placeholder="qualified_rate"/><small>Stable identifier used by Key Results and measurement adapters.</small></label><label className="wide">Label<input value={formulaEntry.label} onChange={e=>setFormulaEntry({...formulaEntry,label:e.target.value})}/></label><label className="wide">Formula expression<input value={formulaEntry.expression} onChange={e=>setFormulaEntry({...formulaEntry,expression:e.target.value})} placeholder="100 * qualified_count / researched_count"/><small>Declarative calculation contract—not executable JavaScript or SQL.</small></label><label className="wide">Calculation description<textarea rows="3" value={formulaEntry.description} onChange={e=>setFormulaEntry({...formulaEntry,description:e.target.value})}/></label><button className="btn primary" disabled={busy||!formulaEntry.source_id||!formulaEntry.id||!formulaEntry.label||!formulaEntry.expression} onClick={()=>save(formulaEntry,()=>setFormulaEntry(emptyFormula))}>Save formula</button></div></article></section>
    {ruleTemplate&&<section className="this-week-card"><div className="objective-section-head"><div><h2>Cross-system measurement rule</h2><p className="digest-muted">Reference mapping across Web Crawler MCP, Gmail connector, CRM and ERP.</p></div>{ruleInstalled?<span className="objective-status status-on_track">Installed</span>:<button className="btn primary" disabled={busy||!ruleTemplate.validation?.schema_valid} onClick={()=>save(ruleTemplate,()=>{})}>Install reference rule</button>}</div><h3>{ruleTemplate.label}</h3><p>{ruleTemplate.description}</p><code>{ruleTemplate.expression}</code><div className="objective-attribute-list">{ruleTemplate.mappings.map(mapping=><article key={`${mapping.source_id}-${mapping.attribute_id}`}><div><strong>{registry.sources.find(source=>source.id===mapping.source_id)?.label} · {mapping.object_id}</strong><code>{mapping.attribute_id}</code><small>Path: {registry.sources.find(source=>source.id===mapping.source_id)?.objects?.find(object=>object.id===mapping.object_id)?.attributes?.find(field=>field.id===mapping.attribute_id)?.path} · Correlation: {mapping.correlation_key}</small></div></article>)}</div><p><span className={`objective-status ${ruleTemplate.validation?.schema_valid?'status-on_track':'status-blocked'}`}>{ruleTemplate.validation?.schema_valid?'Schema validated':'Invalid mapping'}</span> <span className="objective-status status-not_started">Evaluator not connected</span></p></section>}
    <section className="this-week-card"><h2>Company-managed entries</h2>{!custom.length&&!registry.rules?.length?<p className="digest-muted">No company-specific entries yet.</p>:<><div className="objective-registry-list">{custom.map(item=><details className="objective-registry-source" key={item.id}><summary><span><strong>{item.label}</strong><small>{item.id} · {item.provider}</small></span><span>{item.attributes.length} attributes · {item.formulas.length} formulas</span></summary><div className="objective-attribute-list"><h4>Supported attributes</h4>{item.attributes.map(entry=><article key={entry.id}><div><strong>{entry.label}</strong><code>{entry.id}</code><small>{pretty(entry.data_type)} · {entry.object_id} → {entry.path}</small></div><button className="danger-link" onClick={()=>remove('attribute',entry.id)}>Remove</button></article>)}</div><div className="objective-formula-list"><h4>Formulas</h4>{item.formulas.map(entry=><article key={entry.id}><div><strong>{entry.label}</strong><code>{entry.expression}</code><small>{entry.id} · {entry.description}</small></div><button className="danger-link" onClick={()=>remove('formula',entry.id)}>Remove</button></article>)}</div><button className="danger-link" onClick={()=>remove('source',item.id)}>Remove source</button></details>)}</div>{registry.rules?.map(rule=><article className="objective-registry-source" key={rule.id}><div className="objective-section-head"><div><strong>{rule.label}</strong><small>{rule.mappings.length} mapped systems · {rule.validation?.schema_valid?'schema validated':'invalid'}</small></div><button className="danger-link" onClick={()=>remove('composite_rule',rule.id)}>Remove rule</button></div><code>{rule.expression}</code><p className="digest-muted">Evaluator not connected; this rule is stored as a validated mapping contract and is not yet calculating Key Results.</p></article>)}</>}</section>
    <section className="this-week-card"><h2>Platform baseline</h2><p className="digest-muted">Available to this company automatically; supported attributes, object paths and formulas are inherited and read-only.</p><div className="objective-registry-list">{system.map(item=><details className="objective-registry-source" key={item.id}><summary><span><strong>{item.label}</strong><small>{item.category} · {item.provider}</small></span><span><span>{item.attributes.length} attributes · {item.formulas.length} formulas</span><span className={`objective-status ${item.availability==='available'?'status-on_track':'status-not_started'}`}>{pretty(item.availability)}</span></span></summary>{item.objects?.length>0&&<div className="objective-attribute-list"><h4>Provider object catalogue</h4>{item.objects.map(object=><article key={object.id}><div><strong>{object.label}</strong><code>{object.id}</code><small>{object.provider_object}</small></div></article>)}</div>}<div className="objective-attribute-list"><h4>Supported attributes</h4>{item.attributes.map(entry=><article key={entry.id}><div><strong>{entry.label}</strong><code>{entry.id}</code><small>{pretty(entry.data_type)} · {entry.object_id?`${entry.object_id} → ${entry.path}`:entry.description}</small></div>{entry.company_managed&&<button className="danger-link" onClick={()=>remove('attribute',entry.id)}>Remove company attribute</button>}</article>)}</div><div className="objective-formula-list"><h4>Validated formulas</h4>{item.formulas.map(entry=><article key={entry.id}><div><strong>{entry.label}</strong><code>{entry.expression}</code><small>{entry.id} · {entry.description}</small></div><span className={`objective-status ${entry.validation?.valid?'status-on_track':'status-blocked'}`}>{entry.validation?.valid?'Validated':'Invalid'}</span>{entry.company_managed&&<button className="danger-link" onClick={()=>remove('formula',entry.id)}>Remove company formula</button>}</article>)}</div></details>)}</div></section>
  </div>;
}

export function ObjectiveDetail() {
  const {objectiveId}=useParams(); const [objective,setObjective]=useState(null),[versions,setVersions]=useState([]),[evidence,setEvidence]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[runBusy,setRunBusy]=useState(''),[message,setMessage]=useState('');
  const load=()=>Promise.all([api.companyObjectiveGet(objectiveId),api.companyObjectiveVersions(objectiveId),api.companyObjectiveEvidenceList(objectiveId,{limit:25,offset:0})]).then(([o,v,e])=>{setObjective(o.objective);setVersions(v.versions||[]);setEvidence(e.evidence||[]);}).catch(e=>setError(e.message));
  useEffect(()=>{load();},[objectiveId]);
  const status=async(next)=>{setBusy(true);try{await api.companyObjectiveUpdate(objectiveId,{status:next,reason:`CEO changed status to ${next}`});await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const runAdhoc=async(goal)=>{setRunBusy(goal.id);setError('');setMessage('');try{const result=await api.companyObjectiveRunInitiativeGoal(objectiveId,goal.id);setMessage(`Goal Plan started: ${result.goal_run_id}`);await load();}catch(e){setError(e.message);}finally{setRunBusy('');}};
  if(!objective&&!error)return <p>Loading objective…</p>; if(!objective)return <div className="error-box">{error}</div>;
  const revenue=objective.revenue||{};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">{objective.name}</h1><p className="digest-sub">{objective.period_label} · {pretty(objective.status)} · version {objective.version}</p></div><div className="digest-header-tools"><button className="btn secondary" disabled={busy||runBusy} onClick={load}>Refresh evidence</button>{objective.status!=='active'&&<button className="btn primary" disabled={busy} onClick={()=>status('active')}>Activate</button>}{objective.status==='active'&&<button className="btn secondary" disabled={busy} onClick={()=>status('paused')}>Pause</button>}<button className="btn secondary" disabled={busy} onClick={()=>status('completed')}>Close objective</button></div></header>{error&&<div className="error-box">{error}</div>}{message&&<div className="success-box" role="status">{message}</div>}
    <section className="this-week-card"><div className="objective-card-top"><span className={`objective-status status-${objective.health}`}>{pretty(objective.health)}</span><span>Budget {money(objective.budget_amount,objective.currency)}</span></div><h2>Outcome</h2><p>{objective.outcome}</p><p><strong>Authority:</strong> research {objective.authority?.internal_research}; CRM writes {objective.authority?.reversible_crm_writes}; external communication {pretty(objective.authority?.external_communications)}.</p></section>
    <section className="objective-metric-grid">{[['Researched',revenue.researched],['Qualified',revenue.qualified],['Rejected',revenue.rejected],['Awaiting approval',revenue.awaiting_approval],['Weighted pipeline',money(revenue.weighted_pipeline,objective.currency)],['Cost',money(revenue.cost,objective.currency)]].map(([l,v])=><article className="this-week-card" key={l}><small>{l}</small><h2>{v||0}</h2></article>)}</section>
    <section className="this-week-card"><div className="objective-section-head"><div><h2>Key results</h2><p className="digest-muted">Business systems measure these automatically from CRM, evidence and cost telemetry.</p></div><span className="objective-status status-on_track">Autonomous measurement</span></div><div className="objective-kr-list">{objective.key_results.map(k=><article key={k.id}><div><strong>{k.name}</strong><span>{k.current_value} / {k.target} {k.unit}</span></div><Progress value={k.progress_pct}/><small>{k.definition||`Measured from ${pretty(k.source_type)}`} · Source: {pretty(k.source_type)} · Confidence {k.confidence}</small></article>)}</div></section>
    <section className="this-week-card objective-execution-tree"><div className="objective-section-head"><div><h2>Initiatives and execution</h2><p className="digest-muted">The objective defines success. Initiatives organize the work. Scheduled and one-off Goal Plans execute it and retain evidence.</p></div><div className="objective-run-stats"><span>{objective.execution_summary?.scheduled_goals||0} scheduled</span><span>{objective.execution_summary?.goal_plan_runs||0} runs</span><span>{objective.execution_summary?.completed_runs||0} completed</span></div></div>
      <div className="objective-tree-root"><span>Objective</span><strong>{objective.name}</strong></div>
      <div className="objective-initiative-list">{objective.initiatives.map((i,index)=><article className="objective-initiative-branch" key={i.id}><div className="objective-initiative-heading"><span className="objective-tree-number">{index+1}</span><div><strong>{i.name}</strong><p>{i.owner_label} · {i.cadence||'On demand'} · {pretty(i.status)}</p></div></div><p>{i.prompt}</p>
        {i.scheduled_goals?.map(s=><div className="objective-execution-node scheduled" key={s.id}><div><span className="objective-node-label">Scheduled Goal</span><strong>{s.title}</strong><small>{pretty(s.cadence)} at {s.time_local} · {pretty(s.status)} · runs autonomously until the objective ends</small></div><Link className="btn secondary" to="/scheduled-goals">Open schedule</Link><div className="objective-run-list">{s.goal_plan_runs?.length?s.goal_plan_runs.map((g,n)=><Link key={g.goal_run_id} to={`/goal-plans/${encodeURIComponent(g.goal_run_id)}`}><span>Goal Plan run {s.goal_plan_runs.length-n}</span><small>{pretty(g.status)} · {new Date(g.created_at).toLocaleString()}</small></Link>):<p className="digest-muted">Goal Plan runs will appear here automatically after each scheduled execution.</p>}</div></div>)}
        <div className="objective-execution-node adhoc"><span className="objective-node-label">Ad-hoc Goals</span>{i.goals?.filter(g=>g.goal_type==='adhoc'&&g.enabled).map(g=><div className="objective-adhoc-definition" key={g.id}><div><strong>{g.title}</strong><small>{g.owner_label||'COO'} · contributes to {(g.linked_key_result_ids||[]).length} Key Result(s)</small></div><button className="btn primary" disabled={objective.status!=='active'||runBusy===g.id} onClick={()=>runAdhoc(g)}>{runBusy===g.id?'Starting…':'Run goal'}</button></div>)}{i.adhoc_goal_plans?.length?<div className="objective-run-list">{i.adhoc_goal_plans.map(g=><Link key={g.goal_run_id} to={`/goal-plans/${encodeURIComponent(g.goal_run_id)}`}><span>{g.title||'One-off Goal Plan'}</span><small>{pretty(g.status)} · {new Date(g.created_at).toLocaleString()}</small></Link>)}</div>:<p className="digest-muted">No ad-hoc Goal Plan runs yet.</p>}</div>
      </article>)}</div>
    </section>
    <section className="this-week-card"><details open><summary><strong>Evidence, constraints and decision history</strong></summary><p>{revenue.evidence_records||0} traceable evidence records from business events and Goal Plan execution.</p>{evidence.length?<ol>{evidence.map(e=><li key={e.id}><strong>{pretty(e.record_type)}</strong> · {e.account_name||e.external_id} · {pretty(e.status)} · {new Date(e.occurred_at).toLocaleString()}{e.metadata?.provenance&&' · provenance retained'}</li>)}</ol>:<p className="digest-muted">No evidence recorded yet.</p>}<ul>{objective.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul><h3>Versions</h3><ol>{versions.map(v=><li key={v.id}>v{v.version} · {v.reason||'updated'} · {v.created_at}</li>)}</ol></details></section>
  </div>;
}
