import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api';

const PAGE = 12;
const periods = [['monthly','Monthly'],['quarterly','Quarterly'],['half_yearly','Half-yearly'],['annual','Annual']];
const money = (value, currency = 'SGD') => new Intl.NumberFormat('en-SG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value) || 0);
const pretty = (value) => String(value || '').replaceAll('_', ' ');
const today = new Date().toISOString().slice(0, 10);
const endOfYear = `${new Date().getFullYear()}-12-31`;

function Progress({ value = 0 }) { return <div className="objective-progress" aria-label={`${value}% complete`}><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }

export function ObjectivesList() {
  const [page, setPage] = useState(0), [period, setPeriod] = useState(''), [status, setStatus] = useState('');
  const [data, setData] = useState({ objectives: [], total: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [demoBusy, setDemoBusy] = useState(false);
  const load = () => { setLoading(true); api.companyObjectivesList({ limit: PAGE, offset: page * PAGE, period_type: period, status }).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, [page, period, status]);
  return <div className="digest-page objectives-page"><header className="digest-header"><div><h1 className="digest-title">Objectives</h1><p className="digest-sub">Turn company outcomes into measurable key results, continuing initiatives and governed execution.</p></div><div className="digest-header-tools"><Link className="btn primary" to="/objectives/new">New objective</Link><button className="btn secondary" disabled={demoBusy} onClick={async()=>{setDemoBusy(true);setError('');try{await api.companyObjectiveBootstrapNorthstar();load();}catch(e){setError(e.message);}finally{setDemoBusy(false);}}}>{demoBusy?'Setting up…':'Set up Northstar demo'}</button></div></header>
    <section className="this-week-card objective-filters"><label>Period<select value={period} onChange={(e)=>{setPeriod(e.target.value);setPage(0);}}><option value="">All periods</option>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(0);}}><option value="">All statuses</option>{['draft','active','paused','completed'].map(v=><option key={v}>{v}</option>)}</select></label></section>
    {error&&<div className="error-box">{error}</div>}{loading?<p>Loading objectives…</p>:data.objectives.length===0?<section className="empty-state"><h2>No objectives yet</h2><p>Create one in Objective Studio or install the safe reference demo.</p></section>:<div className="objective-card-grid">{data.objectives.map(o=>{const lead=o.key_results?.[0];return <Link className="this-week-card objective-card" to={`/objectives/${encodeURIComponent(o.id)}`} key={o.id}><div className="objective-card-top"><span className={`objective-status status-${o.health}`}>{pretty(o.health)}</span><span>{o.period_label}</span></div><h2>{o.name}</h2><p>{o.outcome}</p>{lead&&<><Progress value={lead.progress_pct}/><strong>{lead.current_value} / {lead.target} {lead.unit}</strong></>}<footer><span>{o.key_results?.length||0} key results</span><span>{o.initiatives?.length||0} initiatives</span><span>{o.revenue?.awaiting_approval||0} approvals</span></footer></Link>;})}</div>}
    <div className="objective-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.total?`${page*PAGE+1}–${Math.min(data.total,(page+1)*PAGE)} of ${data.total}`:'0'}</span><button disabled={!data.has_more} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </div>;
}

export function ObjectiveStudio() {
  const navigate=useNavigate(); const [form,setForm]=useState({outcome:'Generate S$100k qualified pipeline this quarter. Target Singapore SMEs. Do not send external communications without approval.',period_type:'quarterly',period_label:'Q4 2026',starts_on:'2026-10-01',ends_on:'2026-12-31',currency:'SGD',budget_amount:450});
  const [proposal,setProposal]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[model,setModel]=useState('');
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const ideate=async()=>{setBusy(true);setError('');try{const r=await api.companyObjectiveIdeate(form);setProposal(r.proposal);setModel(r.model_used+(r.fallback?' · safe fallback':''));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const save=async(status)=>{setBusy(true);setError('');try{const p=proposal||form;const r=await api.companyObjectiveCreate({...p,period_type:p.period_type||p.periodType,period_label:p.period_label||p.periodLabel,starts_on:p.starts_on||p.startsOn,ends_on:p.ends_on||p.endsOn,status});navigate(`/objectives/${encodeURIComponent(r.objective.id)}`);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">Objective Studio</h1><p className="digest-sub">Define what success means before Goal Plans decide how to execute it.</p></div></header>{error&&<div className="error-box">{error}</div>}
    <section className="this-week-card objective-studio-form"><label className="wide">Business outcome<textarea rows="4" value={form.outcome} onChange={e=>set('outcome',e.target.value)}/></label><label>Period<select value={form.period_type} onChange={e=>set('period_type',e.target.value)}>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Period label<input value={form.period_label} onChange={e=>set('period_label',e.target.value)}/></label><label>Starts<input type="date" value={form.starts_on||today} onChange={e=>set('starts_on',e.target.value)}/></label><label>Ends<input type="date" value={form.ends_on||endOfYear} onChange={e=>set('ends_on',e.target.value)}/></label><label>Currency<input value={form.currency} maxLength="8" onChange={e=>set('currency',e.target.value)}/></label><label>AI/tool budget<input type="number" min="0" value={form.budget_amount} onChange={e=>set('budget_amount',Number(e.target.value))}/></label><div className="wide"><button className="btn primary" disabled={busy||!form.outcome.trim()} onClick={ideate}>{busy?'Designing…':'Generate objective proposal'}</button></div></section>
    {proposal&&<section className="this-week-card objective-proposal"><div className="objective-pulse-head"><div><h2>{proposal.name}</h2><p>{proposal.outcome}</p></div><small>{model}</small></div><h3>Key results</h3><div className="objective-kr-list">{proposal.key_results?.map((k,i)=><article key={i}><strong>{k.name}</strong><span>Target {k.target} {k.unit}</span><small>Source: {k.source_type} · Formula: {k.formula}</small></article>)}</div><h3>Initiatives</h3><ol>{proposal.initiatives?.map((i,n)=><li key={n}><strong>{i.name}</strong> — {i.owner_label} · {i.cadence}</li>)}</ol><h3>Authority and constraints</h3><p>Internal research: allowed · reversible CRM writes: allowed · external communication: approval required</p><ul>{proposal.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul><div className="objective-actions"><button className="btn secondary" disabled={busy} onClick={()=>save('draft')}>Save draft</button><button className="btn primary" disabled={busy} onClick={()=>save('active')}>Approve and operate</button></div></section>}
  </div>;
}

export function ObjectiveDetail() {
  const {objectiveId}=useParams(); const [objective,setObjective]=useState(null),[versions,setVersions]=useState([]),[evidence,setEvidence]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[goalId,setGoalId]=useState('');
  const [approval,setApproval]=useState({channel:'email',recipients:'',content:''});
  const load=()=>Promise.all([api.companyObjectiveGet(objectiveId),api.companyObjectiveVersions(objectiveId),api.companyObjectiveEvidenceList(objectiveId,{limit:25,offset:0})]).then(([o,v,e])=>{setObjective(o.objective);setVersions(v.versions||[]);setEvidence(e.evidence||[]);}).catch(e=>setError(e.message));
  useEffect(()=>{load();},[objectiveId]);
  const status=async(next)=>{setBusy(true);try{await api.companyObjectiveUpdate(objectiveId,{status:next,reason:`CEO changed status to ${next}`});await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  if(!objective&&!error)return <p>Loading objective…</p>; if(!objective)return <div className="error-box">{error}</div>;
  const revenue=objective.revenue||{};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">{objective.name}</h1><p className="digest-sub">{objective.period_label} · {pretty(objective.status)} · version {objective.version}</p></div><div className="digest-header-tools">{objective.status!=='active'&&<button className="btn primary" disabled={busy} onClick={()=>status('active')}>Activate</button>}{objective.status==='active'&&<button className="btn secondary" disabled={busy} onClick={()=>status('paused')}>Pause</button>}<button className="btn secondary" disabled={busy} onClick={()=>status('completed')}>Close objective</button></div></header>{error&&<div className="error-box">{error}</div>}
    <section className="this-week-card"><div className="objective-card-top"><span className={`objective-status status-${objective.health}`}>{pretty(objective.health)}</span><span>Budget {money(objective.budget_amount,objective.currency)}</span></div><h2>Outcome</h2><p>{objective.outcome}</p><p><strong>Authority:</strong> research {objective.authority?.internal_research}; CRM writes {objective.authority?.reversible_crm_writes}; external communication {pretty(objective.authority?.external_communications)}.</p></section>
    <section className="objective-metric-grid">{[['Researched',revenue.researched],['Qualified',revenue.qualified],['Rejected',revenue.rejected],['Awaiting approval',revenue.awaiting_approval],['Weighted pipeline',money(revenue.weighted_pipeline,objective.currency)],['Cost',money(revenue.cost,objective.currency)]].map(([l,v])=><article className="this-week-card" key={l}><small>{l}</small><h2>{v||0}</h2></article>)}</section>
    <section className="this-week-card"><h2>Key results</h2><div className="objective-kr-list">{objective.key_results.map(k=><article key={k.id}><div><strong>{k.name}</strong><span>{k.current_value} / {k.target} {k.unit}</span></div><Progress value={k.progress_pct}/><small>{k.definition||`Source: ${k.source_type}`} · Confidence {k.confidence}</small><button className="btn secondary" onClick={async()=>{const value=window.prompt(`Current value for ${k.name}`,k.current_value);if(value===null)return;await api.companyObjectiveMeasure(objective.id,k.id,{value:Number(value),source_type:'manual',source_id:`ui-${Date.now()}`,confidence:'medium'});load();}}>Record measurement</button></article>)}</div></section>
    <section className="this-week-card"><h2>Initiatives</h2><div className="objective-initiative-list">{objective.initiatives.map(i=><article key={i.id}><strong>{i.name}</strong><span>{i.owner_label} · {i.cadence||'On demand'} · {pretty(i.status)}</span><p>{i.prompt}</p></article>)}</div></section>
    <section className="this-week-card"><h2>Goal Plan execution</h2><form className="objective-link-goal" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.companyObjectiveLinkGoal(objective.id,{goal_run_id:goalId});setGoalId('');await load();}catch(x){setError(x.message);}finally{setBusy(false);}}}><input value={goalId} onChange={e=>setGoalId(e.target.value)} placeholder="Link an existing agr-… Goal Plan"/><button disabled={!goalId||busy}>Link</button></form>{objective.goal_runs.length?<ul>{objective.goal_runs.map(g=><li key={g.goal_run_id}><Link to={`/goal-plans/${encodeURIComponent(g.goal_run_id)}`}>{g.title||g.goal_run_id}</Link> · {g.status||'linked'}</li>)}</ul>:<p className="digest-muted">No Goal Plans linked yet. Existing planner behavior is unchanged; link its durable run here.</p>}</section>
    <section className="this-week-card"><h2>External communication approvals</h2><p className="digest-muted">A grant is bound to the exact channel, recipients and content hash. Editing any of them requires a new approval.</p><form className="objective-approval-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api.companyObjectiveApprovalCreate(objective.id,{channel:approval.channel,recipients:approval.recipients.split(',').map(x=>x.trim()).filter(Boolean),content:approval.content});setApproval(a=>({...a,content:''}));await load();}catch(x){setError(x.message);}finally{setBusy(false);}}}><select value={approval.channel} onChange={e=>setApproval(a=>({...a,channel:e.target.value}))}><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="linkedin">LinkedIn</option></select><input value={approval.recipients} onChange={e=>setApproval(a=>({...a,recipients:e.target.value}))} placeholder="Recipients, comma separated"/><textarea rows="3" value={approval.content} onChange={e=>setApproval(a=>({...a,content:e.target.value}))} placeholder="Exact content to approve"/><button disabled={busy||!approval.recipients.trim()||!approval.content.trim()}>Request approval</button></form><div className="objective-approval-list">{objective.approvals?.map(a=><article key={a.id}><div><strong>{pretty(a.status)}</strong> · {a.channel} · {a.recipients.join(', ')}</div><small>Expires {new Date(a.expires_at).toLocaleString()} · used {a.used_count}/{a.max_uses} · hash {a.content_hash.slice(0,12)}…</small>{a.status==='pending'&&<div className="objective-actions"><button className="btn primary" disabled={busy} onClick={async()=>{await api.companyObjectiveApprovalDecide(objective.id,a.id,'approved');load();}}>Approve exact batch</button><button className="btn secondary" disabled={busy} onClick={async()=>{await api.companyObjectiveApprovalDecide(objective.id,a.id,'rejected');load();}}>Reject</button></div>}</article>)}</div></section>
    <section className="this-week-card"><details><summary><strong>Evidence, constraints and decision history</strong></summary><p>{revenue.evidence_records||0} revenue evidence records.</p>{evidence.length?<ol>{evidence.map(e=><li key={e.id}><strong>{pretty(e.record_type)}</strong> · {e.account_name||e.external_id} · {pretty(e.status)} · {new Date(e.occurred_at).toLocaleString()}</li>)}</ol>:<p className="digest-muted">No evidence recorded yet.</p>}<ul>{objective.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul><h3>Versions</h3><ol>{versions.map(v=><li key={v.id}>v{v.version} · {v.reason||'updated'} · {v.created_at}</li>)}</ol></details></section>
  </div>;
}
