import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api';

const PAGE = 12;
const periods = [['monthly','Monthly'],['quarterly','Quarterly'],['half_yearly','Half-yearly'],['annual','Annual']];
const money = (value, currency = 'SGD') => new Intl.NumberFormat('en-SG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value) || 0);
const pretty = (value) => String(value || '').replaceAll('_', ' ');
const today = new Date().toISOString().slice(0, 10);
const endOfYear = `${new Date().getFullYear()}-12-31`;

function Progress({ value = 0 }) { return <div className="objective-progress" aria-label={`${value}% complete`}><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }

export function ObjectivesList() {
  const [page, setPage] = useState(0), [period, setPeriod] = useState(''), [status, setStatus] = useState('');
  const [data, setData] = useState({ objectives: [], total: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [demoBusy, setDemoBusy] = useState(false);
  const load = () => { setLoading(true); api.companyObjectivesList({ limit: PAGE, offset: page * PAGE, period_type: period, status }).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, [page, period, status]);
  return <div className="digest-page objectives-page"><header className="digest-header"><div><h1 className="digest-title">Objectives</h1><p className="digest-sub">Turn company outcomes into measurable key results, continuing initiatives and governed execution.</p></div><div className="digest-header-tools"><Link className="btn primary" to="/objectives/new">New objective</Link><button className="btn secondary" disabled={demoBusy} onClick={async()=>{setDemoBusy(true);setError('');try{await api.companyObjectiveBootstrapNorthstar();load();}catch(e){setError(e.message);}finally{setDemoBusy(false);}}}>{demoBusy?'Setting up…':'Set up Northstar demo'}</button></div></header>
    <section className="this-week-card objective-filters"><label>Period<select value={period} onChange={(e)=>{setPeriod(e.target.value);setPage(0);}}><option value="">All periods</option>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(0);}}><option value="">All statuses</option>{['draft','active','paused','completed'].map(v=><option key={v}>{v}</option>)}</select></label></section>
    {error&&<div className="error-box">{error}</div>}{loading?<p>Loading objectives…</p>:data.objectives.length===0?<section className="empty-state"><h2>No objectives yet</h2><p>Create one in Objective Studio or install the safe reference demo.</p></section>:<div className="objective-card-grid">{data.objectives.map(o=>{const lead=o.key_results?.[0];return <Link className="this-week-card objective-card" to={`/objectives/${encodeURIComponent(o.id)}`} key={o.id}><div className="objective-card-top"><span className={`objective-status status-${o.health}`}>{pretty(o.health)}</span><span>{o.period_label}</span></div><h2>{o.name}</h2><p>{o.outcome}</p>{lead&&<><Progress value={lead.progress_pct}/><strong>{lead.current_value} / {lead.target} {lead.unit}</strong></>}<footer><span>{o.key_results?.length||0} key results</span><span>{o.initiatives?.length||0} initiatives</span><span>{o.revenue?.awaiting_approval||0} approvals</span></footer></Link>;})}</div>}
    <div className="objective-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.total?`${page*PAGE+1}–${Math.min(data.total,(page+1)*PAGE)} of ${data.total}`:'0'}</span><button disabled={!data.has_more} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </div>;
}

export function ObjectiveStudio() {
  const navigate=useNavigate(); const [form,setForm]=useState({outcome:'Generate S$100k qualified pipeline this quarter. Target Singapore SMEs. Do not send external communications without approval.',period_type:'quarterly',period_label:'Q4 2026',starts_on:'2026-10-01',ends_on:'2026-12-31',currency:'SGD',budget_amount:450});
  const [proposal,setProposal]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[model,setModel]=useState('');
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const updateKr=(index,patch)=>setProposal(p=>({...p,key_results:p.key_results.map((item,n)=>n===index?{...item,...patch}:item)}));
  const addKr=()=>setProposal(p=>({...p,key_results:[...(p.key_results||[]),{name:'New measurable result',definition:'',baseline:0,target:1,current_value:0,unit:'count',source_type:'revenue_evidence',formula:'researched',confidence:'medium'}]}));
  const updateInitiative=(index,patch)=>setProposal(p=>({...p,initiatives:p.initiatives.map((item,n)=>n===index?{...item,...patch}:item)}));
  const addInitiative=()=>setProposal(p=>({...p,initiatives:[...(p.initiatives||[]),{name:'New initiative',owner_label:'COO',cadence:'On demand',prompt:'',status:'draft'}]}));
  const move=(key,index,direction)=>setProposal(p=>{const items=[...(p[key]||[])],to=index+direction;if(to<0||to>=items.length)return p;[items[index],items[to]]=[items[to],items[index]];return {...p,[key]:items};});
  const ideate=async()=>{setBusy(true);setError('');try{const r=await api.companyObjectiveIdeate(form);setProposal(r.proposal);setModel(r.model_used+(r.fallback?' · safe fallback':''));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const save=async(status)=>{setBusy(true);setError('');try{const p=proposal||form;const r=await api.companyObjectiveCreate({...p,period_type:p.period_type||p.periodType,period_label:p.period_label||p.periodLabel,starts_on:p.starts_on||p.startsOn,ends_on:p.ends_on||p.endsOn,status});navigate(`/objectives/${encodeURIComponent(r.objective.id)}`);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">Objective Studio</h1><p className="digest-sub">Define what success means before Goal Plans decide how to execute it.</p></div></header>{error&&<div className="error-box">{error}</div>}
    <section className="this-week-card objective-studio-form"><label className="wide">Business outcome<textarea rows="4" value={form.outcome} onChange={e=>set('outcome',e.target.value)}/></label><label>Period<select value={form.period_type} onChange={e=>set('period_type',e.target.value)}>{periods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Period label<input value={form.period_label} onChange={e=>set('period_label',e.target.value)}/></label><label>Starts<input type="date" value={form.starts_on||today} onChange={e=>set('starts_on',e.target.value)}/></label><label>Ends<input type="date" value={form.ends_on||endOfYear} onChange={e=>set('ends_on',e.target.value)}/></label><label>Currency<input value={form.currency} maxLength="8" onChange={e=>set('currency',e.target.value)}/></label><label>AI/tool budget<input type="number" min="0" value={form.budget_amount} onChange={e=>set('budget_amount',Number(e.target.value))}/></label><div className="wide"><button className="btn primary" disabled={busy||!form.outcome.trim()} onClick={ideate}>{busy?'Designing…':'Generate objective proposal'}</button></div></section>
    {proposal&&<section className="this-week-card objective-proposal"><div className="objective-pulse-head"><div><h2>{proposal.name}</h2><p>{proposal.outcome}</p></div><small>{model}</small></div>
      <div className="objective-editor-heading"><div><h3>Key results</h3><p>Define measurable outcomes. Flolah updates each result from its selected business-data source.</p></div><button className="btn secondary" type="button" onClick={addKr}>Add key result</button></div>
      <div className="objective-edit-list">{proposal.key_results?.map((k,i)=><article className="objective-edit-card" key={`kr-${i}`}><div className="objective-edit-card-top"><span>KR {i+1}</span><div><button type="button" disabled={i===0} onClick={()=>move('key_results',i,-1)} aria-label={`Move key result ${i+1} up`}>↑</button><button type="button" disabled={i===proposal.key_results.length-1} onClick={()=>move('key_results',i,1)} aria-label={`Move key result ${i+1} down`}>↓</button><button type="button" className="danger-link" onClick={()=>setProposal(p=>({...p,key_results:p.key_results.filter((_,n)=>n!==i)}))}>Remove</button></div></div><label className="wide">Result name<input value={k.name||''} onChange={e=>updateKr(i,{name:e.target.value})}/></label><label>Baseline<input type="number" value={k.baseline??0} onChange={e=>updateKr(i,{baseline:Number(e.target.value)})}/></label><label>Target<input type="number" min="0" value={k.target??0} onChange={e=>updateKr(i,{target:Number(e.target.value)})}/></label><label>Unit<input value={k.unit||''} onChange={e=>updateKr(i,{unit:e.target.value})}/></label><label>Measurement source<select value={k.source_type||'revenue_evidence'} onChange={e=>updateKr(i,{source_type:e.target.value})}><option value="crm">CRM</option><option value="revenue_evidence">Execution evidence</option><option value="llmops">AI/tool telemetry</option><option value="manual">Manual exception</option></select></label><label>Measurement formula<select value={k.formula||''} onChange={e=>updateKr(i,{formula:e.target.value})}><option value="weighted_pipeline">Weighted pipeline</option><option value="researched">Researched accounts</option><option value="qualified">Qualified accounts</option><option value="drafts">Outreach drafts</option><option value="positive_responses">Positive responses</option><option value="cost">AI/tool cost</option></select></label><label className="wide">Definition<input value={k.definition||''} onChange={e=>updateKr(i,{definition:e.target.value})} placeholder="Exactly what counts and where the evidence comes from"/></label></article>)}</div>
      <div className="objective-editor-heading"><div><h3>Initiatives</h3><p>Define the coordinated bodies of work that will produce the Key Results. Scheduling happens beneath each initiative.</p></div><button className="btn secondary" type="button" onClick={addInitiative}>Add initiative</button></div>
      <div className="objective-edit-list">{proposal.initiatives?.map((item,i)=><article className="objective-edit-card" key={`initiative-${i}`}><div className="objective-edit-card-top"><span>Initiative {i+1}</span><div><button type="button" disabled={i===0} onClick={()=>move('initiatives',i,-1)} aria-label={`Move initiative ${i+1} up`}>↑</button><button type="button" disabled={i===proposal.initiatives.length-1} onClick={()=>move('initiatives',i,1)} aria-label={`Move initiative ${i+1} down`}>↓</button><button type="button" className="danger-link" onClick={()=>setProposal(p=>({...p,initiatives:p.initiatives.filter((_,n)=>n!==i)}))}>Remove</button></div></div><label className="wide">Initiative name<input value={item.name||''} onChange={e=>updateInitiative(i,{name:e.target.value})}/></label><label>Accountable owner<input value={item.owner_label||''} onChange={e=>updateInitiative(i,{owner_label:e.target.value})}/></label><label>Cadence or trigger<input value={item.cadence||''} onChange={e=>updateInitiative(i,{cadence:e.target.value})} placeholder="Weekdays 09:00, event driven, or on demand"/></label><label className="wide">Execution brief<textarea rows="2" value={item.prompt||''} onChange={e=>updateInitiative(i,{prompt:e.target.value})}/></label></article>)}</div>
      <details className="objective-boundaries"><summary><strong>Objective-specific execution boundaries</strong></summary><p>These boundaries narrow execution for this outcome. They cannot override company Policy, employee work assignments, or Exception Policy.</p><dl><div><dt>Company Policy</dt><dd>Controls what is permitted across the company.</dd></div><div><dt>Work assignments</dt><dd>Control which employee or agent is responsible and what tools they may use.</dd></div><div><dt>Exception Policy</dt><dd>Controls what happens when work is blocked, uncertain, or outside authority.</dd></div><div><dt>This Objective</dt><dd>Adds narrower limits such as budget, approved market, and no external sends without approval.</dd></div></dl><ul>{proposal.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul></details>
      <div className="objective-actions"><button className="btn secondary" disabled={busy||!proposal.key_results?.length} onClick={()=>save('draft')}>Save draft</button><button className="btn primary" disabled={busy||!proposal.key_results?.length||!proposal.initiatives?.length} onClick={()=>save('active')}>Approve and operate</button></div></section>}
  </div>;
}

export function ObjectiveDetail() {
  const {objectiveId}=useParams(); const [objective,setObjective]=useState(null),[versions,setVersions]=useState([]),[evidence,setEvidence]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.companyObjectiveGet(objectiveId),api.companyObjectiveVersions(objectiveId),api.companyObjectiveEvidenceList(objectiveId,{limit:25,offset:0})]).then(([o,v,e])=>{setObjective(o.objective);setVersions(v.versions||[]);setEvidence(e.evidence||[]);}).catch(e=>setError(e.message));
  useEffect(()=>{load();},[objectiveId]);
  const status=async(next)=>{setBusy(true);try{await api.companyObjectiveUpdate(objectiveId,{status:next,reason:`CEO changed status to ${next}`});await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  if(!objective&&!error)return <p>Loading objective…</p>; if(!objective)return <div className="error-box">{error}</div>;
  const revenue=objective.revenue||{};
  return <div className="digest-page objectives-page"><header className="digest-header"><div><Link to="/objectives">← Objectives</Link><h1 className="digest-title">{objective.name}</h1><p className="digest-sub">{objective.period_label} · {pretty(objective.status)} · version {objective.version}</p></div><div className="digest-header-tools">{objective.status!=='active'&&<button className="btn primary" disabled={busy} onClick={()=>status('active')}>Activate</button>}{objective.status==='active'&&<button className="btn secondary" disabled={busy} onClick={()=>status('paused')}>Pause</button>}<button className="btn secondary" disabled={busy} onClick={()=>status('completed')}>Close objective</button></div></header>{error&&<div className="error-box">{error}</div>}
    <section className="this-week-card"><div className="objective-card-top"><span className={`objective-status status-${objective.health}`}>{pretty(objective.health)}</span><span>Budget {money(objective.budget_amount,objective.currency)}</span></div><h2>Outcome</h2><p>{objective.outcome}</p><p><strong>Authority:</strong> research {objective.authority?.internal_research}; CRM writes {objective.authority?.reversible_crm_writes}; external communication {pretty(objective.authority?.external_communications)}.</p></section>
    <section className="objective-metric-grid">{[['Researched',revenue.researched],['Qualified',revenue.qualified],['Rejected',revenue.rejected],['Awaiting approval',revenue.awaiting_approval],['Weighted pipeline',money(revenue.weighted_pipeline,objective.currency)],['Cost',money(revenue.cost,objective.currency)]].map(([l,v])=><article className="this-week-card" key={l}><small>{l}</small><h2>{v||0}</h2></article>)}</section>
    <section className="this-week-card"><div className="objective-section-head"><div><h2>Key results</h2><p className="digest-muted">Business systems measure these automatically from CRM, evidence and cost telemetry.</p></div><span className="objective-status status-on_track">Autonomous measurement</span></div><div className="objective-kr-list">{objective.key_results.map(k=><article key={k.id}><div><strong>{k.name}</strong><span>{k.current_value} / {k.target} {k.unit}</span></div><Progress value={k.progress_pct}/><small>{k.definition||`Measured from ${pretty(k.source_type)}`} · Source: {pretty(k.source_type)} · Confidence {k.confidence}</small></article>)}</div></section>
    <section className="this-week-card objective-execution-tree"><div className="objective-section-head"><div><h2>Initiatives and execution</h2><p className="digest-muted">The objective defines success. Initiatives organize the work. Scheduled and one-off Goal Plans execute it and retain evidence.</p></div><div className="objective-run-stats"><span>{objective.execution_summary?.scheduled_goals||0} scheduled</span><span>{objective.execution_summary?.goal_plan_runs||0} runs</span><span>{objective.execution_summary?.completed_runs||0} completed</span></div></div>
      <div className="objective-tree-root"><span>Objective</span><strong>{objective.name}</strong></div>
      <div className="objective-initiative-list">{objective.initiatives.map((i,index)=><article className="objective-initiative-branch" key={i.id}><div className="objective-initiative-heading"><span className="objective-tree-number">{index+1}</span><div><strong>{i.name}</strong><p>{i.owner_label} · {i.cadence||'On demand'} · {pretty(i.status)}</p></div></div><p>{i.prompt}</p>
        {i.scheduled_goals?.map(s=><div className="objective-execution-node scheduled" key={s.id}><div><span className="objective-node-label">Scheduled Goal</span><strong>{s.title}</strong><small>{pretty(s.cadence)} at {s.time_local} · {pretty(s.status)} · runs autonomously until the objective ends</small></div><Link className="btn secondary" to="/scheduled-goals">Open schedule</Link><div className="objective-run-list">{s.goal_plan_runs?.length?s.goal_plan_runs.map((g,n)=><Link key={g.goal_run_id} to={`/goal-plans/${encodeURIComponent(g.goal_run_id)}`}><span>Goal Plan run {s.goal_plan_runs.length-n}</span><small>{pretty(g.status)} · {new Date(g.created_at).toLocaleString()}</small></Link>):<p className="digest-muted">Goal Plan runs will appear here automatically after each scheduled execution.</p>}</div></div>)}
        <div className="objective-execution-node adhoc"><span className="objective-node-label">Ad-hoc Goal Plans</span>{i.adhoc_goal_plans?.length?<div className="objective-run-list">{i.adhoc_goal_plans.map(g=><Link key={g.goal_run_id} to={`/goal-plans/${encodeURIComponent(g.goal_run_id)}`}><span>{g.title||'One-off Goal Plan'}</span><small>{pretty(g.status)} · {new Date(g.created_at).toLocaleString()}</small></Link>)}</div>:<p className="digest-muted">No one-off execution for this initiative.</p>}</div>
      </article>)}</div>
    </section>
    <section className="this-week-card"><details><summary><strong>Evidence, constraints and decision history</strong></summary><p>{revenue.evidence_records||0} revenue evidence records.</p>{evidence.length?<ol>{evidence.map(e=><li key={e.id}><strong>{pretty(e.record_type)}</strong> · {e.account_name||e.external_id} · {pretty(e.status)} · {new Date(e.occurred_at).toLocaleString()}</li>)}</ol>:<p className="digest-muted">No evidence recorded yet.</p>}<ul>{objective.constraints?.map((c,i)=><li key={i}>{c}</li>)}</ul><h3>Versions</h3><ol>{versions.map(v=><li key={v.id}>v{v.version} · {v.reason||'updated'} · {v.created_at}</li>)}</ol></details></section>
  </div>;
}
