import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { MarketSubscriptions } from '../src/market-subscriptions.js';
import { rankSP500Top100Profiles, selectUniverseProfiles } from '../src/core.js';

let now = Date.parse('2026-10-05T15:00:00Z'); const ib = new EventEmitter(); const requests = []; const cancelled = []; const events = [];
ib.reqRealTimeBars = (...args) => requests.push(['bars', ...args]);
ib.reqMktData = (...args) => requests.push(['quotes', ...args]);
ib.cancelRealTimeBars = id => cancelled.push(['bars', id]); ib.cancelMktData = id => cancelled.push(['quotes', id]);
let regular = true;
const manager = new MarketSubscriptions(ib, p => ({ symbol: p.symbol, conId: p.con_id || 0 }), (type, p) => events.push([type, p]), { now: () => now, regular: () => regular, starts: [] });
manager.setProfiles([{ symbol: 'EEM', security_type: 'ETF' }, { symbol: 'TLT', security_type: 'ETF' }]);
assert.equal(requests.length, 4);
const first = { ...manager.entries.get('EEM') };
assert.equal(requests[1][4], false, 'no regulatory snapshots');
ib.emit('error', new Error('DU999999 sensitive broker message'), 10197, first.quoteId);
assert.equal(events.at(-1)[1].code, '10197'); assert.ok(!JSON.stringify(events).includes('DU999999'));
now += 29999; manager.refresh(); assert.equal(requests.length, 4, 'bounded cooldown');
now += 1; manager.refresh(); assert.equal(requests.length, 6, 'failed subscription automatically retries');
assert.equal(ib.listenerCount('realtimeBar'), 1, 'refresh does not multiply callbacks');
assert.ok(cancelled.some(x => x[1] === first.barId));
ib.emit('realtimeBar', first.barId, now / 1000, 1, 1, 1, 1, 1, 1, 1);
assert.equal(events.filter(x => x[0] === 'market.realtime_bar').length, 0, 'retired callbacks ignored');
const e = manager.entries.get('EEM');
ib.emit('marketDataType', e.quoteId, 1); ib.emit('tickPrice', e.quoteId, 1, 68); ib.emit('tickPrice', e.quoteId, 2, 68.01);
ib.emit('realtimeBar', e.barId, now / 1000, 68, 68.01, 68, 68.01, 1, 68, 1);
assert.ok(manager.health().healthy_symbols.includes('EEM'));
ib.emit('marketDataType', e.quoteId, 3);
assert.ok(manager.health().pending_symbols.includes('EEM'), 'delayed data never reports execution-ready feed');
ib.emit('marketDataType', e.quoteId, 1);
const before = requests.length; manager.setProfiles([{ symbol: 'EEM', security_type: 'ETF', assets_under_management_usd: 1e9 }]);
assert.equal(requests.length, before, 'slow profile update does not restart healthy streams');
assert.ok(!manager.entries.has('TLT'), 'removed universe symbol unsubscribed');
now += 61000; manager.refresh(); assert.equal(requests.length, before + 2, 'silent stream stall retries');
regular = false; now += 300000; manager.refresh(); assert.equal(requests.length, before + 2, 'no closed-session retries');
regular = true;
manager.setProfiles(Array.from({ length: 100 }, (_, i) => ({ symbol: `TEST${i}`, security_type: 'STK' })));
assert.equal(manager.starts.length, 50, 'initial plus retry requests paced below 60/ten minutes');
assert.ok(manager.health().pending_symbols.length > 0, 'pacing wait not reported healthy');
assert.equal(ib.listenerCount('tickPrice'), 1, '100 symbols use one dispatcher');
manager.dispose(); assert.equal(ib.listenerCount('tickPrice'), 0); assert.equal(ib.listenerCount('error'), 0);

const at = new Date(now).toISOString();
const members = Array.from({ length: 503 }, (_, i) => ({ symbol: `S${String(i).padStart(3, '0')}`, security_type: 'STK', index_memberships: ['SPX'], membership_at: at, market_cap_at: at, fundamentals: { market_cap_usd: 1e12 - i * 1e8 } }));
const ranked = rankSP500Top100Profiles(members, now);
assert.equal(ranked.filter(p => p.index_memberships.includes('SPX_TOP100')).length, 100);
assert.equal(ranked[0].sp500_market_cap_rank, 1);
assert.throws(() => rankSP500Top100Profiles(members.slice(0, 70), now), /Complete/);
assert.throws(() => rankSP500Top100Profiles([...members.slice(0, -1), members[0]], now), /unique/);
assert.throws(() => rankSP500Top100Profiles(members.map((p, i) => i ? p : { ...p, market_cap_at: '2026-09-01T00:00:00Z' }), now), /Current/);
assert.throws(() => rankSP500Top100Profiles(members.map((p, i) => i ? p : { ...p, fundamentals: {} }), now), /Current/);
assert.throws(() => rankSP500Top100Profiles(members.map((p, i) => i ? p : { ...p, membership_at: new Date(now + 1000).toISOString() }), now), /Current/);
// Selection uses current timestamp, not a fixture clock invented for production.
const freshMembers = members.map(p => ({ ...p, membership_at: new Date().toISOString(), market_cap_at: new Date().toISOString() }));
const universe = { filters: { stock: { enabled: true, indexes: ['SPX_TOP100'], index_match: 'ANY' }, etf: { enabled: true, categories: ['EQUITY'] } } };
const selected = selectUniverseProfiles([...freshMembers, { symbol: 'EEM', security_type: 'ETF', etf_categories: ['EQUITY'] }], universe);
assert.equal(selected.length, 101); assert.equal(selected[0].symbol, 'S000'); assert.ok(selected.some(p => p.symbol === 'EEM'));
console.log('IBKRNew subscriptions passed: permission/session recovery, stale-stream retry, pacing, cleanup, profile reload, complete/fresh top-100 ranking. No broker connection/orders.');
