import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { dailyVolumeProfile, VolumeProfiles } from '../src/volume-profiles.js';

let now = Date.parse('2026-10-05T15:00:00Z');
const bars = Array.from({ length: 25 }, (_, i) => ({ date: new Date(Date.parse('2026-09-01') + i * 86400000).toISOString().slice(0, 10).replaceAll('-', ''), volume: 2000000 + i * 1000 }));
bars.push({ date: '20261002', volume: 3000000 }, { date: '20261005', volume: 999999999 });
const volume = dailyVolumeProfile(bars, now);
assert.equal(volume.average_daily_volume_last_session, '20261002');
assert.equal(volume.average_daily_volume_sessions, 20);
assert.ok(volume.average_daily_volume < 3000000, 'exclude the incomplete current session; no x100 unit inflation');
assert.equal(volume.average_daily_volume, dailyVolumeProfile([...bars, bars[0]], now).average_daily_volume, 'deduplicate sessions');
assert.throws(() => dailyVolumeProfile(bars.slice(0, 10), now), /INSUFFICIENT/);
assert.throws(() => dailyVolumeProfile([...bars, { date: '20261001', volume: -1 }], now), /INVALID/);
assert.throws(() => dailyVolumeProfile(bars, now + 20 * 86400000), /STALE/);

const ib = new EventEmitter(); const requests = []; const cancelled = []; const events = [];
ib.reqHistoricalData = (...args) => requests.push(args); ib.cancelHistoricalData = id => cancelled.push(id);
const manager = new VolumeProfiles(ib, p => ({ symbol: p.symbol }), (type, payload) => events.push([type, payload]), { now: () => now });
manager.setProfiles([{ symbol: 'AAPL', security_type: 'STK' }, { symbol: 'JPM', security_type: 'STK' }, { symbol: 'TLT', security_type: 'ETF' }]);
assert.equal(requests.length, 1); assert.equal(manager.entries.size, 2, 'stock-only: volume does not renew ETF profile age');
for (const bar of bars) ib.emit('historicalData', requests[0][0], bar.date, 1, 1, 1, 1, bar.volume);
ib.emit('historicalData', requests[0][0], 'finished', 0, 0, 0, 0, 0);
ib.emit('historicalDataEnd', requests[0][0]);
assert.equal(events.length, 1, 'legacy and modern end callbacks publish once');
assert.ok(manager.get('AAPL')); assert.ok(!('fundamentals' in events[0][1])); assert.ok(!('corporate_events' in events[0][1]));
manager.refresh(); assert.equal(requests.length, 1, 'bounded pacing');
now += 12000; manager.refresh(); assert.equal(requests.length, 2);
ib.emit('error', new Error('DU123456 private'), 162, requests[1][0]);
assert.equal(manager.health().details.find(d => d.symbol === 'JPM').reason, 'IBKR_162');
assert.ok(!JSON.stringify(events).includes('DU123456'), 'raw provider errors never emitted');
now += 30000; manager.refresh(); assert.equal(requests.length, 2, 'error backoff');
now += 600000; manager.refresh(); const timeoutId = requests.at(-1)[0]; now += 30000; manager.refresh();
assert.ok(cancelled.includes(timeoutId), 'timeout retires data request');
assert.equal(events.at(-1)[1].code, 'DAILY_HISTORY_TIMEOUT');
now += 36 * 3600000 + 1; assert.equal(manager.get('AAPL'), null, 'stale cached volume cannot enrich entry features');
manager.dispose(); assert.equal(ib.listenerCount('historicalData'), 0);
const pacing = new VolumeProfiles(ib, p => p, () => {}, { now: () => now });
pacing.starts = Array.from({ length: 50 }, () => now - 20000); pacing.setProfiles([{ symbol: 'AAPL', security_type: 'STK' }]);
assert.equal(pacing.active, null, '50 starts/10 minutes maximum'); pacing.dispose();
console.log('IBKRNew volume profiles passed: units, completion, deduplication, freshness, pacing, errors, removal and cleanup. No orders.');
